/**
 * Offline reproduction script generator.
 * ======================================
 *
 * Turns an experiment record into a self-contained `backtest.py` a researcher
 * can run outside this app — numpy plus the standard library, nothing else
 * (`statistics.NormalDist` covers the PSR/MinTRL math scipy would otherwise
 * provide). The script pins the historical window via the klines `endTime`, so
 * it re-fetches the bars the run actually saw; Binance history is immutable,
 * though the final bar of the original run may have still been forming, so the
 * header states expected metrics with a tolerance rather than asserting them.
 *
 * The ported logic mirrors `engine.ts` exactly, including the two pinned
 * parity details: exit dominates entry, and NaN comparisons are false.
 */

import type { ExperimentRecord } from "./experiments";

/** JSON value → Python literal. The three keywords differ; everything else
 *  (numbers, strings, arrays, objects) is JSON-compatible. */
export function pyLiteral(value: unknown): string {
  if (value === null || value === undefined) return "None";
  if (typeof value === "boolean") return value ? "True" : "False";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "None";
  if (typeof value === "string") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(pyLiteral).join(", ")}]`;
  if (typeof value === "object") {
    return `{${Object.entries(value as Record<string, unknown>)
      .map(([k, v]) => `${JSON.stringify(k)}: ${pyLiteral(v)}`)
      .join(", ")}}`;
  }
  throw new Error(`cannot render a ${typeof value} as a Python literal`);
}

const STRATEGY_BODIES: Record<string, string> = {
  ma_cross: `    f = sma(close, fast)
    s = sma(close, slow)
    state = np.zeros(len(close), dtype=np.int8)
    both = ~np.isnan(f) & ~np.isnan(s)
    state[both & (f > s)] = 1
    return state`,
  donchian: `    upper = shift1(rolling_max(high, fast))   # breakout trigger
    lower = shift1(rolling_min(low, slow))    # trailing exit
    state = np.zeros(len(close), dtype=np.int8)
    cur = 0
    for i in range(len(close)):
        if not math.isnan(upper[i]) and close[i] > upper[i]:
            cur = 1
        if not math.isnan(lower[i]) and close[i] < lower[i]:
            cur = 0  # exit overrides entry
        state[i] = cur
    return state`,
  rsi_reversion: `    r = rsi(close, fast)
    trend = sma(close, slow)   # a STOP, not an entry gate
    state = np.zeros(len(close), dtype=np.int8)
    cur = 0
    for i in range(len(close)):
        if not math.isnan(r[i]) and r[i] < 30:
            cur = 1
        if (not math.isnan(r[i]) and r[i] > 55) or (
            not math.isnan(trend[i]) and close[i] < trend[i]
        ):
            cur = 0  # exit overrides entry
        state[i] = cur
    return state`,
};

export function generatePythonScript(
  record: ExperimentRecord,
  meta: { appCommit?: string | null } = {},
): string {
  const body = STRATEGY_BODIES[record.strategy];
  if (!body) throw new Error(`unknown strategy "${record.strategy}"`);

  const req = record.request;
  // Strict format check before Date.parse — V8's lenient parser would happily
  // turn junk into the year 2000 and silently pin the wrong window.
  if (!/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$/.test(record.periodEnd)) {
    throw new Error(`unparseable period end "${record.periodEnd}"`);
  }
  const endTimeMs = Date.parse(`${record.periodEnd.replace(" ", "T")}:00Z`);
  if (!Number.isFinite(endTimeMs)) {
    throw new Error(`unparseable period end "${record.periodEnd}"`);
  }
  const savedIso = new Date(record.savedAt).toISOString();

  return `#!/usr/bin/env python3
"""AlphaEngine offline reproduction — ${record.id} (${record.symbol} ${record.interval}).

Generated by the research portal${meta.appCommit ? ` at commit ${meta.appCommit}` : ""}.
Run recorded ${savedIso}; original dataset fingerprint ${record.dataHash ?? "n/a"}
(cited for provenance — this script fingerprints its own fetch).

Expected metrics from the recorded run (the final bar of the original window
may still have been forming, so allow small drift on a re-fetch):
    sharpe ${record.sharpe.toFixed(4)} · return ${(record.totalReturn * 100).toFixed(2)}% · max DD ${(record.maxDrawdown * 100).toFixed(2)}% · trades ${record.trades}

Dependencies: numpy (pip install numpy). Everything else is stdlib.
"""

import json
import math
import urllib.request
from statistics import NormalDist

import numpy as np

REQUEST = ${pyLiteral(req)}
FAST = ${record.fast}
SLOW = ${record.slow}
END_TIME_MS = ${endTimeMs}  # ${record.periodEnd} UTC — pins the historical window

BARS_PER_YEAR = {"1m": 525600, "5m": 105120, "15m": 35040, "30m": 17520,
                 "1h": 8760, "2h": 4380, "4h": 2190, "1d": 365, "1w": 52}
HOURS_PER_BAR = {"1m": 1 / 60, "5m": 5 / 60, "15m": 0.25, "30m": 0.5,
                 "1h": 1.0, "2h": 2.0, "4h": 4.0, "1d": 24.0, "1w": 168.0}
BINANCE = "https://data-api.binance.vision/api/v3/klines"


def fetch_klines(symbol, interval, bars, end_time_ms):
    """Paginate backwards from end_time_ms until enough bars are collected."""
    out = []
    end = end_time_ms
    while len(out) < bars:
        limit = min(1000, bars - len(out))
        url = f"{BINANCE}?symbol={symbol}&interval={interval}&limit={limit}&endTime={end}"
        with urllib.request.urlopen(url, timeout=15) as resp:
            chunk = json.loads(resp.read())
        if not chunk:
            break
        out = chunk + out
        end = chunk[0][0] - 1
        if len(chunk) < limit:
            break
    rows = out[-bars:]
    return {
        "t": np.array([r[0] for r in rows], dtype=np.int64),
        "o": np.array([float(r[1]) for r in rows]),
        "h": np.array([float(r[2]) for r in rows]),
        "l": np.array([float(r[3]) for r in rows]),
        "c": np.array([float(r[4]) for r in rows]),
        "v": np.array([float(r[5]) for r in rows]),
    }


# ---------------------------------------------------------------- indicators
def sma(x, period):
    out = np.full(len(x), np.nan)
    if 0 < period <= len(x):
        c = np.cumsum(np.insert(x, 0, 0.0))
        out[period - 1:] = (c[period:] - c[:-period]) / period
    return out


def rolling_max(x, period):
    out = np.full(len(x), np.nan)
    for i in range(period - 1, len(x)):
        out[i] = x[i - period + 1: i + 1].max()
    return out


def rolling_min(x, period):
    out = np.full(len(x), np.nan)
    for i in range(period - 1, len(x)):
        out[i] = x[i - period + 1: i + 1].min()
    return out


def shift1(x):
    return np.concatenate([[np.nan], x[:-1]])


def rsi(close, period):
    """Wilder RSI, seeded from the first delta — mirrors the TS engine."""
    n = len(close)
    out = np.full(n, np.nan)
    if period <= 0 or n < 2:
        return out
    alpha = 1.0 / period
    avg_gain = avg_loss = 0.0
    for i in range(1, n):
        delta = close[i] - close[i - 1]
        gain = delta if delta > 0 else 0.0
        loss = -delta if delta < 0 else 0.0
        if i == 1:
            avg_gain, avg_loss = gain, loss
        else:
            avg_gain += alpha * (gain - avg_gain)
            avg_loss += alpha * (loss - avg_loss)
        out[i] = 100.0 if avg_loss == 0 else 100.0 - 100.0 / (1.0 + avg_gain / avg_loss)
    return out


# ------------------------------------------------------------------- signals
def long_state(close, high, low, fast, slow):
    """Should-be-long per bar. Exit dominates entry; NaN comparisons are False."""
${body}


def build_position(close, high, low, fast, slow, direction):
    """Event-driven target position: 1 long, 0 flat, -1 short (long_short)."""
    is_long = long_state(close, high, low, fast, slow)
    flat = -1 if direction == "long_short" else 0
    pos = np.zeros(len(close))
    state = 0
    prev = 0
    for i in range(len(close)):
        if is_long[i] and not prev:
            state = 1
        elif not is_long[i] and prev:
            state = flat
        pos[i] = state
        prev = is_long[i]
    return pos


# --------------------------------------------------------------------- costs
def average_daily_volume(bars, interval):
    quote = float((bars["v"] * bars["c"]).sum()) / max(1, len(bars["c"]))
    return quote * 24.0 / HOURS_PER_BAR.get(interval, 1.0)


def turnover_cost(req, adv):
    flat = (req["feeBps"] + req["slippageBps"]) / 1e4
    k = req.get("impactCoefficient") or 0
    notional = req.get("orderNotional") or 0
    if k <= 0 or notional <= 0 or adv <= 0:
        return flat
    participation = min(1.0, notional / adv)
    return flat + k * math.sqrt(participation)


def holding_cost(req, position, interval):
    hours = HOURS_PER_BAR.get(interval, 1.0)
    funding = ((req.get("fundingBpsPer8h") or 0) / 1e4) * (hours / 8.0) * abs(position)
    borrow = (
        ((req.get("borrowBpsAnnual") or 0) / 1e4) * (hours / 8760.0) * abs(position)
        if position < 0
        else 0.0
    )
    return funding + borrow


# ------------------------------------------------------------------- metrics
def annualised_sharpe(returns, ann):
    sd = returns.std(ddof=1)
    return float(returns.mean() / sd * math.sqrt(ann)) if sd > 0 else 0.0


def max_drawdown(equity):
    peak = np.maximum.accumulate(equity)
    return float((equity / peak - 1.0).min())


def skewness(x):
    n = len(x)
    sd = x.std(ddof=1)
    if n < 3 or sd == 0:
        return 0.0
    return float(n / ((n - 1) * (n - 2)) * (((x - x.mean()) / sd) ** 3).sum())


def kurtosis(x):
    """Raw Pearson kurtosis (normal = 3), small-sample adjusted."""
    n = len(x)
    sd = x.std(ddof=1)
    if n < 4 or sd == 0:
        return 3.0
    g2 = (n * (n + 1)) / ((n - 1) * (n - 2) * (n - 3)) * (((x - x.mean()) / sd) ** 4).sum() \\
        - 3 * (n - 1) ** 2 / ((n - 2) * (n - 3))
    return float(g2 + 3.0)


def psr_and_mintrl(returns, confidence=0.95):
    """Probabilistic Sharpe vs 0 and Minimum Track Record Length (López de Prado)."""
    n = len(returns)
    sd = returns.std(ddof=1)
    sr = float(returns.mean() / sd) if sd > 0 else 0.0
    skew, kurt = skewness(returns), kurtosis(returns)
    var_term = max(1e-12, 1 - skew * sr + (kurt - 1) / 4 * sr * sr)
    psr = NormalDist().cdf(sr * math.sqrt(n - 1) / math.sqrt(var_term)) if n > 2 else 0.0
    if sr <= 0:
        mintrl = math.inf
    else:
        z = NormalDist().inv_cdf(confidence)
        mintrl = 1 + var_term * (z / sr) ** 2
    return psr, mintrl


# ----------------------------------------------------------------------- run
def main():
    bars = fetch_klines(REQUEST["symbol"], REQUEST["interval"], REQUEST["bars"], END_TIME_MS)
    close, high, low = bars["c"], bars["h"], bars["l"]
    n = len(close)
    ann = BARS_PER_YEAR.get(REQUEST["interval"], 8760)

    px_ret = np.zeros(n)
    px_ret[1:] = np.where(close[:-1] != 0, close[1:] / close[:-1] - 1.0, 0.0)

    pos = build_position(close, high, low, FAST, SLOW, REQUEST["direction"])
    adv = average_daily_volume(bars, REQUEST["interval"])
    cost = turnover_cost(REQUEST, adv)

    lagged = np.concatenate([[0.0], pos[:-1]])  # signal at t, executed at t+1
    turnover = np.abs(np.diff(np.concatenate([[0.0], lagged])))
    holding = np.array([holding_cost(REQUEST, p, REQUEST["interval"]) for p in lagged])
    returns = lagged * px_ret - turnover * cost - holding
    equity = np.cumprod(1.0 + returns)

    trades = int((turnover > 0).sum())  # position *changes*; pairs ≈ recorded trades
    years = n / ann
    total = float(equity[-1] - 1.0)
    cagr = (1.0 + total) ** (1.0 / years) - 1.0 if years > 0 and total > -1 else 0.0
    psr, mintrl = psr_and_mintrl(returns)

    print(f"{REQUEST['symbol']} {REQUEST['interval']} {REQUEST['strategy']} "
          f"{FAST}/{SLOW} over {n} bars ({years:.2f}y)")
    print(f"  total return      {total * 100:+.2f}%   (recorded ${(record.totalReturn * 100).toFixed(2)}%)")
    print(f"  CAGR              {cagr * 100:+.2f}%")
    print(f"  annualised Sharpe {annualised_sharpe(returns, ann):.3f}    (recorded ${record.sharpe.toFixed(3)})")
    print(f"  max drawdown      {max_drawdown(equity) * 100:.2f}%   (recorded ${(record.maxDrawdown * 100).toFixed(2)}%)")
    print(f"  position changes  {trades}   (recorded round-trips ${record.trades})")
    print(f"  PSR vs 0          {psr:.4f}")
    print("  MinTRL @95%       " + ("unreachable (SR <= 0)" if math.isinf(mintrl)
          else f"{mintrl:.0f} bars (~{mintrl / ann:.2f}y); window has {n}"))


if __name__ == "__main__":
    main()
`;
}
