// Generated by scripts/generate-gateway-client.ts from tools/openapi.json — do not edit.
// Typed bindings for the committed gateway contract (OpenAPI 3.1.0).
// Regenerate: node --import tsx scripts/generate-gateway-client.ts

export interface AuditOperationsSnapshot {
  available: boolean;
  backend: string;
}

export interface BacktestRequest {
  bars?: number;
  direction?: "long_only" | "long_short";
  embargo_bars?: number;
  fast_max?: number;
  fast_min?: number;
  fast_step?: number;
  fee_bps?: number;
  folds?: number;
  interval?: string;
  label?: string | null;
  notify_chat_id?: string | null;
  slippage_bps?: number;
  slow_max?: number;
  slow_min?: number;
  slow_step?: number;
  strategy?: "ma_cross" | "ema_cross" | "macd_cross" | "donchian" | "donchian_mid" | "breakout_sma" | "rsi_reversion" | "williams_r" | "stochastic" | "momentum" | "roc_trend" | "triple_ma" | "ppo_cross" | "trix_cross" | "rsi_trend" | "price_channel" | "ema_slope" | "bollinger_breakout" | "zscore_reversion" | "atr_breakout" | "keltner_breakout" | "supertrend" | "atr_trailing_stop" | "obv_trend" | "volume_breakout" | "mfi_reversion" | "dema_cross" | "tema_cross" | "zlema_cross" | "hull_trend" | "vwap_trend" | "cci_reversion" | "awesome_cross" | "cmo_trend" | "stoch_rsi_x" | "dpo_reversion" | "bollinger_pctb" | "stddev_channel" | "chaikin_volatility" | "ulcer_filter" | "cmf_trend" | "force_index" | "eom_trend" | "aroon_cross" | "vortex_cross" | "linreg_forecast";
  symbol?: string;
  walk_forward?: boolean;
}

export interface Body_telegram_link_status_telegram_link_status_post {
  probe: string;
}

export interface BookLevel {
  cum_notional: number;
  notional: number;
  price: number;
  size: number;
}

export interface CancelRequest {
  reason?: string;
}

export interface CheckResult {
  detail: string;
  limit?: number | null;
  name: string;
  observed?: number | null;
  passed: boolean;
}

export interface DataBackfillRequest {
  from_at: string;
  interval?: "15m" | "1h" | "4h" | "1d";
  symbol: string;
  to_at: string;
}

export interface DataJobAccepted {
  backend: string;
  job_id: string;
  kind: "data.replay" | "data.backfill" | "ml.fit";
  poll: string;
  status: string;
}

export interface DataJobView {
  actor?: string;
  backend?: string;
  error?: string | null;
  finished_at?: string | null;
  job_id: string;
  kind: string;
  message?: string;
  params?: Record<string, unknown>;
  progress?: number;
  started_at?: string | null;
  status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
  submitted_at: string;
  summary?: Record<string, unknown> | null;
}

export interface DataJobsResponse {
  backend: string;
  executor_configured: boolean;
  jobs: Array<DataJobView>;
  observed_at: string;
  restored_from_audit?: number;
  retained_in_process: boolean;
}

export interface DataQualityCapabilityRow {
  capability: string;
  drift: number;
  evaluated: number;
  fatal: number;
  not_evaluated: number;
  passed: number;
  warn: number;
}

export interface DataQualityCounts {
  drift: number;
  evaluated: number;
  fatal: number;
  not_evaluated: number;
  passed: number;
  warn: number;
}

export interface DataQualityEscalationView {
  acknowledged_at: string | null;
  acknowledged_by: string | null;
  channel: "telegram" | "log" | "webhook" | null;
  count: number;
  detail: string;
  evaluated: number | null;
  id: number;
  notified_at: string | null;
  opened_at: string;
  provider: string;
  resolved_at: string | null;
  rule: "fatal_burst" | "fail_rate";
  window_minutes: number;
}

export interface DataQualityFindingView {
  capability: string;
  checks: Array<string>;
  id: number;
  instance: string;
  key: string;
  observed_at: string;
  passed: boolean;
  provider: string;
  severity: "fatal" | "warn" | "drift" | "clean";
  source: "web" | "replay" | "backfill";
  symbol: string | null;
}

export interface DataQualityFindingsResponse {
  findings: Array<DataQualityFindingView>;
  observed_at: string;
  retention_days: number;
  total: number;
  window_minutes: number;
}

export interface DataQualityProviderRow {
  drift: number;
  evaluated: number;
  fail_rate: number | null;
  fatal: number;
  not_evaluated: number;
  passed: number;
  provider: string;
  warn: number;
}

export interface DataQualityView {
  backend: "sqlite" | "postgres";
  by_capability: Array<DataQualityCapabilityRow>;
  by_provider: Array<DataQualityProviderRow>;
  escalations: Array<DataQualityEscalationView>;
  first_observed_at: string | null;
  instances: number;
  last_observed_at: string | null;
  observed_at: string;
  recent: Array<DataQualityFindingView>;
  retention_days: number;
  schema_version?: 1;
  total: DataQualityCounts;
  window_minutes: number;
}

export interface DataReplayRequest {
  bars?: number;
  capability?: "quote" | "bars" | "news" | "fundamentals";
  interval?: "15m" | "1h" | "4h" | "1d";
  symbol: string;
}

export interface DataScheduleView {
  cadence: string;
  error: string | null;
  expression: string;
  id: string;
  kind: "replay" | "backfill";
  last_job_id: string | null;
  last_outcome: string | null;
  last_run_at: string | null;
  next_due_at: string | null;
  valid: boolean;
}

export interface DataSchedulesResponse {
  executor_configured: boolean;
  max_backfill_bars: number;
  observed_at: string;
  schedules: Array<DataScheduleView>;
  tick_seconds: number;
}

export interface DecisionLatencySnapshot {
  core_max_ns?: number | null;
  core_p50_ns?: number | null;
  core_p99_ns?: number | null;
  core_self_test_samples?: number | null;
  engine: "native" | "python";
  max_us?: number | null;
  p50_us?: number | null;
  p999_us?: number | null;
  p99_us?: number | null;
  samples: number;
}

export interface EscalationAck {
  acknowledged_by: string | null;
  escalation_id: number;
  taken: boolean;
}

export interface ExecutionEstimate {
  fillable: boolean;
  filled_notional: number;
  filled_qty: number;
  levels_consumed: number;
  mid: number | null;
  slippage_bps: number | null;
  venue: string;
  vwap: number | null;
  worst_price: number | null;
}

export interface Fill {
  fee_usd: number;
  notional: number;
  price: number;
  quantity: number;
  simulated?: boolean;
  slippage_bps: number | null;
  venue: string;
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface KillSwitchRequest {
  reason?: string;
  symbol?: string | null;
}

export interface MLFeatureView {
  feature_count: number;
  label: string;
  label_horizon_bars: number;
  spec: Record<string, unknown>;
  spec_hash: string;
}

export interface MLFitRequest {
  bars?: number;
  cost_bps?: number;
  embargo?: number;
  interval?: "15m" | "1h" | "4h" | "1d";
  label_horizon?: number;
  label_kind?: "return" | "direction" | null;
  model?: "ridge" | "logistic";
  n_splits?: number;
  params?: Record<string, unknown>;
  seed?: number;
  symbol?: string;
}

export interface MLFoldView {
  embargo_bars: number;
  fold_index: number;
  oos_max_drawdown?: number | null;
  oos_return?: number | null;
  oos_sharpe?: number | null;
  purge_bars: number;
  test_end: string;
  test_rows: number;
  test_start: string;
  trades?: number | null;
  train_end: string;
  train_rows: number;
  train_start: string;
}

export interface MLRunDetail {
  data_hash: string;
  deflated_sharpe?: number | null;
  engine: string;
  error?: string | null;
  features?: MLFeatureView | null;
  finished_at?: string | null;
  folds?: Array<MLFoldView>;
  git_sha?: string | null;
  id: string;
  interval: string;
  model: string;
  oos_sharpe?: number | null;
  params?: Record<string, unknown>;
  pbo?: number | null;
  seed: number;
  started_at: string;
  status: string;
  symbol: string;
}

export interface MLRunSummary {
  data_hash: string;
  deflated_sharpe?: number | null;
  engine: string;
  error?: string | null;
  finished_at?: string | null;
  git_sha?: string | null;
  id: string;
  interval: string;
  model: string;
  oos_sharpe?: number | null;
  pbo?: number | null;
  seed: number;
  started_at: string;
  status: string;
  symbol: string;
}

export interface MLRunsResponse {
  observed_at: string;
  runs: Array<MLRunSummary>;
  state: "ok" | "unavailable" | "unreadable";
}

export interface MarketDataFeedSnapshot {
  connected: boolean;
  error_present?: boolean;
  reconnects?: number;
  status: "up" | "degraded" | "stale" | "down";
  symbols?: Array<MarketDataSymbolSnapshot>;
  synthetic?: boolean;
  uptime_seconds?: number;
  venue: string;
}

export interface MarketDataSnapshot {
  enabled: boolean;
  feeds?: Array<MarketDataFeedSnapshot>;
  stale_after_seconds: number;
  status: "nominal" | "degraded" | "critical" | "disabled";
  synthetic_active: boolean;
  uptime_seconds?: number;
}

export interface MarketDataSymbolSnapshot {
  age_seconds?: number | null;
  stale?: boolean;
  symbol: string;
  update_rate_hz?: number;
  updates_total?: number;
}

export interface OnCallSnapshot {
  configured: boolean;
  covered: boolean;
  entries: number;
  invalid: number;
  valid: number;
  webhook_configured: boolean;
}

export interface OperationsSnapshot {
  audit: AuditOperationsSnapshot;
  decision_latency?: DecisionLatencySnapshot | null;
  environment: string;
  market_data: MarketDataSnapshot;
  observed_at: string;
  oncall?: OnCallSnapshot | null;
  queue: QueueOperationsSnapshot;
  risk: RiskOperationsSnapshot;
  route_latency: RouteLatencyOperationsSnapshot;
  schema_version?: 1;
  stale_after_seconds: number;
  status: "nominal" | "degraded" | "critical" | "halted";
  supabase?: SupabaseMirrorSnapshot | null;
  telegram: TelegramOperationsSnapshot;
  version: string;
}

export interface OrderAck {
  actor: string;
  at: string;
  order_id: string;
  reason?: string | null;
  status: "WORKING" | "FILLED" | "CANCELLED" | "EXPIRED" | "REJECTED";
}

export interface OrderEvent {
  actor?: string;
  detail?: string;
  event: string;
  fee_usd?: number | null;
  fill_price?: number | null;
  fill_qty?: number | null;
  replaces?: string | null;
  status: "WORKING" | "FILLED" | "CANCELLED" | "EXPIRED" | "REJECTED";
  ts: string;
  venue?: string | null;
}

export interface OrderRequest {
  client_order_id?: string | null;
  limit_price?: number | null;
  notional?: number | null;
  order_type?: "MARKET" | "LIMIT";
  paper_execution?: PaperExecutionReference | null;
  quantity?: number | null;
  side: "BUY" | "SELL";
  strategy?: string;
  symbol: string;
  time_in_force?: "GTC" | "DAY" | "IOC" | null;
}

export interface OrderTimeline {
  events: Array<OrderEvent>;
  order_id: string;
  status: "WORKING" | "FILLED" | "CANCELLED" | "EXPIRED" | "REJECTED";
}

export interface PaperExecutionReference {
  as_of: string;
  asset_class?: "equity";
  currency?: "USD";
  delayed?: boolean;
  price: number;
  source: string;
}

export interface Position {
  avg_price: number;
  mark_price: number | null;
  notional: number;
  quantity: number;
  realized_pnl: number;
  symbol: string;
  unrealized_pnl: number;
}

export interface QueueOperationsSnapshot {
  backend: string;
  broker_configured: boolean;
  broker_transport?: string | null;
  by_status?: Record<string, number>;
  total: number;
  workers: number;
}

export interface ReduceOnlyRequest {
  enabled?: boolean;
  reason?: string;
  symbol?: string | null;
}

export interface ReplaceRequest {
  limit_price?: number | null;
  notional?: number | null;
  quantity?: number | null;
  reason?: string;
}

export interface ResearchAnswer {
  band?: "answer" | "rewrite" | "refuse" | null;
  calls?: Array<ToolCallView>;
  connected?: Array<ResearchGraphNeighbour>;
  corpus_size?: number | null;
  fallback?: boolean;
  generation?: Record<string, unknown> | null;
  matches?: Array<ResearchRagMatch>;
  planner?: string;
  query: string;
  reasons?: Array<string>;
  refusal?: string | null;
  rerank_state?: string | null;
  reranked?: boolean;
  retrievals?: number;
  rewritten_query?: string | null;
  score?: number | null;
  state: "ok" | "refused" | "unavailable" | "embed_failed";
}

export interface ResearchBoundRefusal {
  correlation_id?: string | null;
  query: string;
  reason: string;
  retry_after_s?: number | null;
  route: string;
  spend?: Record<string, unknown> | null;
  state: "rate_limited" | "spend_capped" | "scope_unavailable";
}

export interface ResearchGraphNeighbour {
  arrived_by: string;
  depth: number;
  evidence?: string | null;
  id: string;
  kind: string;
  occurred_at: string;
  source_ref: string;
  strategy?: string | null;
  symbol?: string | null;
  title: string;
}

export interface ResearchGraphResponse {
  connected: Array<ResearchGraphNeighbour>;
  state: "ok" | "unavailable";
}

export interface ResearchRagAnomalyMatch {
  kind: string;
  occurred_at: string;
  similarity: number;
  title: string;
}

export interface ResearchRagEmbedRequest {
  texts: Array<string>;
}

export interface ResearchRagEmbedResponse {
  dimensions?: number | null;
  embeddings?: Array<Array<number>>;
  model?: string | null;
  state: "ok" | "unavailable";
}

export interface ResearchRagMatch {
  bm25_rank?: number | null;
  body: string;
  id: string;
  kind: string;
  lexical_rank?: number | null;
  metrics?: Record<string, unknown>;
  occurred_at: string;
  rerank_score?: number | null;
  similarity: number;
  source_ref: string;
  strategy?: string | null;
  symbol?: string | null;
  title: string;
  vector_rank?: number | null;
}

export interface ResearchRagSearchRequest {
  kind?: "backtest_run" | "chart" | "execution_summary" | "ml_run" | "risk_incident" | null;
  match_count?: number;
  query: string;
}

export interface ResearchRagSearchResponse {
  bm25?: Record<string, unknown> | null;
  corpus_size?: number | null;
  correlation_id?: string | null;
  image?: Record<string, unknown> | null;
  matches?: Array<ResearchRagMatch>;
  rerank_state?: string | null;
  reranked?: boolean;
  state: "ok" | "unavailable" | "embed_failed";
}

export interface ResearchRagStatus {
  configured: boolean;
  dropped: number;
  failed: number;
  indexed: number;
  last_anomaly_at?: string | null;
  last_anomaly_matches?: Array<ResearchRagAnomalyMatch>;
  pending_embeddings: number;
  queued: number;
  running: boolean;
}

export interface RiskDecision {
  accepted: boolean;
  checks: Array<CheckResult>;
  client_order_id: string | null;
  fill?: Fill | null;
  latency_ms?: number;
  notional: number | null;
  order_id: string;
  quantity: number | null;
  reason?: string | null;
  rejected_by?: Array<string>;
  side: "BUY" | "SELL";
  status?: "WORKING" | "FILLED" | "CANCELLED" | "EXPIRED" | "REJECTED";
  symbol: string;
  time_in_force?: "GTC" | "DAY" | "IOC" | null;
  timestamp: string;
}

export interface RiskOperationsSnapshot {
  daily_drawdown_pct: number;
  drawdown_budget_used_pct: number;
  equity: number;
  gross_exposure: number;
  halted_symbols?: Array<string>;
  kill_switch_active: boolean;
  orders_accepted_total: number;
  orders_last_second: number;
  orders_rejected_total: number;
  reduce_only: boolean;
  status: "nominal" | "reduce_only" | "halted";
  working_orders: number;
}

export interface RiskState {
  carried_realized_pnl?: number;
  daily_drawdown_pct: number;
  daily_pnl: number;
  drawdown_budget_used_pct: number;
  equity: number;
  gross_exposure: number;
  halted_symbols: Array<string>;
  kill_reason: string | null;
  kill_switch_active: boolean;
  killed_at: string | null;
  killed_by: string | null;
  limits: Record<string, number>;
  orders_accepted: number;
  orders_last_second: number;
  orders_rejected: number;
  positions: Array<Position>;
  realized_pnl: number;
  reduce_only?: boolean;
  reduce_only_source?: "threshold" | "operator" | "off";
  reduce_only_threshold?: number;
  session_date: string;
  start_of_day_equity: number;
  unrealized_pnl: number;
  working_notional?: number;
  working_orders?: number;
}

export interface RouteLatencyOperationsSnapshot {
  routes?: Array<RouteLatencySnapshot>;
  window_seconds: number;
}

export interface RouteLatencySnapshot {
  errors_total: number;
  p50_ms: number;
  p95_ms: number;
  p99_ms: number;
  route: string;
  samples: number;
}

export interface RoutingLeg {
  notional: number;
  qty: number;
  share_pct: number;
  venue: string;
  vwap: number;
}

export interface SupabaseMirrorSnapshot {
  configured: boolean;
  dropped: number;
  failed: number;
  last_error_kind?: string | null;
  queued: number;
  running: boolean;
  written: number;
}

export interface TCAReport {
  best_single_venue: string | null;
  consolidated_mid: number | null;
  generated_at: string;
  per_venue: Array<ExecutionEstimate>;
  saving_vs_worst_bps: number | null;
  saving_vs_worst_usd: number | null;
  side: "BUY" | "SELL";
  smart_route: Array<RoutingLeg>;
  smart_route_slippage_bps: number | null;
  smart_route_vwap: number | null;
  symbol: string;
  synthetic?: boolean;
  target_notional: number;
  venues_online: Array<string>;
}

export interface TelegramOperationsSnapshot {
  alerts_sent: number;
  enabled: boolean;
  last_error_kind?: "transport" | "conflict" | "api" | null;
  last_error_present: boolean;
  mode: string;
  status: "running" | "starting" | "degraded" | "disabled";
  updates_handled: number;
  uptime_seconds: number;
}

export interface ToolCallView {
  detail?: string | null;
  reason: string;
  rows: number;
  state: string;
  tool: string;
}

export interface ValidationError {
  ctx?: Record<string, unknown>;
  input?: unknown;
  loc: Array<string | number>;
  msg: string;
  type: string;
}

export interface VenueBook {
  asks?: Array<BookLevel>;
  best_ask?: number | null;
  best_bid?: number | null;
  bids?: Array<BookLevel>;
  connected: boolean;
  depth_usd_ask?: number;
  depth_usd_bid?: number;
  imbalance?: number | null;
  last_update?: string | null;
  latency_ms?: number | null;
  mid?: number | null;
  spread_bps?: number | null;
  stale: boolean;
  symbol: string;
  synthetic?: boolean;
  venue: string;
}

export interface WebContractCheck {
  check: string;
  message?: string;
  severity: "fatal" | "warn" | "drift";
}

export interface WebContractFinding {
  capability: string;
  checks?: Array<WebContractCheck>;
  drift?: number;
  fatal?: number;
  key?: string;
  not_evaluated?: number;
  observed_at: number;
  passed: boolean;
  provider: string;
  seq: number;
  symbol?: string | null;
  warn?: number;
}

export interface WebLatencyBatch {
  key: string;
  samples?: Array<WebLatencySample>;
}

export interface WebLatencyKeyView {
  key: string;
  samples?: Array<WebLatencySample>;
}

export interface WebLatencySample {
  ms: number;
  ok: boolean;
  ts: number;
}

export interface WebOutageCommand {
  expires_at: number;
  note?: string;
  provider: string;
}

export interface WebOutageView {
  expires_at: number;
  note: string;
  provider: string;
}

export interface WebQuotaReset {
  provider: string;
  window: string;
}

export interface WebQuotaSpend {
  provider: string;
  spent: number;
  window: string;
}

export interface WebQuotaView {
  provider: string;
  spent: number;
  window: string;
}

export interface WebStateSyncRequest {
  findings?: Array<WebContractFinding>;
  instance: string;
  latency?: Array<WebLatencyBatch>;
  outages_cleared?: Array<string>;
  outages_set?: Array<WebOutageCommand>;
  quota?: Array<WebQuotaSpend>;
  quota_reset?: Array<WebQuotaReset>;
  schema_version?: 1;
}

export interface WebStateView {
  data_quality: DataQualityView;
  instances: Array<string>;
  latency: Array<WebLatencyKeyView>;
  observed_at: string;
  outages: Array<WebOutageView>;
  quota: Array<WebQuotaView>;
  schema_version?: 1;
  window_seconds: number;
}

export interface WorkItemConflict {
  current: WorkItemView;
  error: "version_conflict";
}

export interface WorkItemCreate {
  area?: string;
  kind: "request" | "ticket" | "bug";
  owner?: string;
  priority: "P0" | "P1" | "P2" | "P3";
  sla_hours?: number | null;
  summary?: string;
  title: string;
}

export interface WorkItemPatch {
  area?: string | null;
  owner?: string | null;
  priority?: "P0" | "P1" | "P2" | "P3" | null;
  status?: "intake" | "ready" | "progress" | "resolved" | null;
  summary?: string | null;
  title?: string | null;
  version: number;
}

export interface WorkItemView {
  area: string;
  created_by: string;
  id: string;
  kind: "request" | "ticket" | "bug";
  opened_at: number;
  owner: string;
  priority: "P0" | "P1" | "P2" | "P3";
  resolved_at: number | null;
  sla_due_at: number | null;
  status: "intake" | "ready" | "progress" | "resolved";
  summary: string;
  title: string;
  updated_at: number;
  updated_by: string;
  version: number;
}

export interface WorkItemsResponse {
  backend: "sqlite" | "postgres";
  count: number;
  items: Array<WorkItemView>;
  observed_at: string;
  seeded: number;
}

export interface WorkingOrder {
  accepted_at: string;
  age_seconds: number;
  client_order_id?: string | null;
  distance_bps?: number | null;
  expires_at?: string | null;
  limit_price: number;
  mark_price?: number | null;
  notional: number;
  order_id: string;
  order_type: "MARKET" | "LIMIT";
  quantity: number;
  side: "BUY" | "SELL";
  source: string;
  status: "WORKING" | "FILLED" | "CANCELLED" | "EXPIRED" | "REJECTED";
  strategy: string;
  symbol: string;
  time_in_force: "GTC" | "DAY" | "IOC";
}

/** Request/response bindings keyed by "METHOD /path". */
export interface GatewayOperations {
  "GET /api/audit/backtests": { response: Array<Record<string, unknown>> };
  "GET /api/audit/events": { response: Array<Record<string, unknown>> };
  "GET /api/audit/orders": { response: Array<Record<string, unknown>> };
  "GET /api/audit/stats": { response: Record<string, unknown> };
  "POST /api/backtest": { request: BacktestRequest; response: Record<string, unknown> };
  "GET /api/book/{symbol}": { response: Array<VenueBook> };
  "GET /api/config": { response: Record<string, unknown> };
  "POST /api/data-quality/escalations/{escalation_id}/ack": { response: EscalationAck };
  "GET /api/data-quality/findings": { response: DataQualityFindingsResponse };
  "GET /api/data-quality/view": { response: DataQualityView };
  "POST /api/data/backfill": { request: DataBackfillRequest; response: DataJobAccepted };
  "GET /api/data/jobs": { response: DataJobsResponse };
  "POST /api/data/replay": { request: DataReplayRequest; response: DataJobAccepted };
  "GET /api/data/schedules": { response: DataSchedulesResponse };
  "GET /api/data/work-items": { response: WorkItemsResponse };
  "POST /api/data/work-items": { request: WorkItemCreate; response: WorkItemView };
  "DELETE /api/data/work-items/{item_id}": { response: WorkItemView };
  "PATCH /api/data/work-items/{item_id}": { request: WorkItemPatch; response: WorkItemView };
  "GET /api/jobs": { response: Record<string, unknown> };
  "GET /api/jobs/{job_id}": { response: Record<string, unknown> };
  "GET /api/ops/snapshot": { response: OperationsSnapshot };
  "POST /api/ops/web-state/sync": { request: WebStateSyncRequest; response: WebStateView };
  "GET /api/orders": { response: Array<WorkingOrder> };
  "POST /api/orders": { request: OrderRequest; response: RiskDecision };
  "GET /api/orders/{order_id}": { response: OrderTimeline };
  "POST /api/orders/{order_id}/cancel": { request: CancelRequest; response: OrderAck };
  "POST /api/orders/{order_id}/replace": { request: ReplaceRequest; response: RiskDecision };
  "GET /api/portfolio": { response: Record<string, unknown> };
  "GET /api/portfolio/history": { response: Record<string, unknown> };
  "GET /api/research/graph/centrality": { response: Record<string, unknown> };
  "GET /api/research/graph/communities": { response: Record<string, unknown> };
  "GET /api/research/graph/{document_id}": { response: ResearchGraphResponse };
  "POST /api/research/ml/fit": { request: MLFitRequest; response: DataJobAccepted };
  "GET /api/research/ml/runs": { response: MLRunsResponse };
  "GET /api/research/ml/runs/{run_id}": { response: MLRunDetail };
  "GET /api/research/openbb/bars": { response: Record<string, unknown> };
  "GET /api/research/openbb/fundamentals": { response: Record<string, unknown> };
  "GET /api/research/openbb/health": { response: Record<string, unknown> };
  "GET /api/research/openbb/news": { response: Record<string, unknown> };
  "GET /api/research/openbb/quote": { response: Record<string, unknown> };
  "POST /api/research/rag/ask": { request: ResearchRagSearchRequest; response: ResearchAnswer };
  "POST /api/research/rag/embed": { request: ResearchRagEmbedRequest; response: ResearchRagEmbedResponse };
  "POST /api/research/rag/search": { request: ResearchRagSearchRequest; response: ResearchRagSearchResponse };
  "GET /api/research/rag/status": { response: ResearchRagStatus };
  "POST /api/risk/kill": { request: KillSwitchRequest; response: Record<string, unknown> };
  "GET /api/risk/limits": { response: Record<string, number> };
  "POST /api/risk/reduce-only": { request: ReduceOnlyRequest; response: Record<string, unknown> };
  "POST /api/risk/reset": { response: Record<string, unknown> };
  "POST /api/risk/resume": { request: KillSwitchRequest; response: Record<string, unknown> };
  "GET /api/risk/state": { response: RiskState };
  "GET /api/stream/desk": { response: unknown };
  "GET /api/tca/{symbol}": { response: TCAReport };
  "GET /health": { response: Record<string, unknown> };
  "GET /metrics": { response: unknown };
  "GET /telegram/health": { response: Record<string, unknown> };
  "POST /telegram/link/status": { request: Body_telegram_link_status_telegram_link_status_post; response: Record<string, unknown> };
  "POST /telegram/webhook": { response: Record<string, boolean> };
}

/** Every path the committed contract publishes. */
export const GATEWAY_CONTRACT_PATHS = [
  "/api/audit/backtests",
  "/api/audit/events",
  "/api/audit/orders",
  "/api/audit/stats",
  "/api/backtest",
  "/api/book/{symbol}",
  "/api/config",
  "/api/data-quality/escalations/{escalation_id}/ack",
  "/api/data-quality/findings",
  "/api/data-quality/view",
  "/api/data/backfill",
  "/api/data/jobs",
  "/api/data/replay",
  "/api/data/schedules",
  "/api/data/work-items",
  "/api/data/work-items/{item_id}",
  "/api/jobs",
  "/api/jobs/{job_id}",
  "/api/ops/snapshot",
  "/api/ops/web-state/sync",
  "/api/orders",
  "/api/orders/{order_id}",
  "/api/orders/{order_id}/cancel",
  "/api/orders/{order_id}/replace",
  "/api/portfolio",
  "/api/portfolio/history",
  "/api/research/graph/centrality",
  "/api/research/graph/communities",
  "/api/research/graph/{document_id}",
  "/api/research/ml/fit",
  "/api/research/ml/runs",
  "/api/research/ml/runs/{run_id}",
  "/api/research/openbb/bars",
  "/api/research/openbb/fundamentals",
  "/api/research/openbb/health",
  "/api/research/openbb/news",
  "/api/research/openbb/quote",
  "/api/research/rag/ask",
  "/api/research/rag/embed",
  "/api/research/rag/search",
  "/api/research/rag/status",
  "/api/risk/kill",
  "/api/risk/limits",
  "/api/risk/reduce-only",
  "/api/risk/reset",
  "/api/risk/resume",
  "/api/risk/state",
  "/api/stream/desk",
  "/api/tca/{symbol}",
  "/health",
  "/metrics",
  "/telegram/health",
  "/telegram/link/status",
  "/telegram/webhook",
] as const;

export type GatewayContractPath = (typeof GATEWAY_CONTRACT_PATHS)[number];
