// Generated by scripts/generate-gateway-client.ts from tools/openapi.json — do not edit.
// Typed bindings for the committed gateway contract (OpenAPI 3.1.0).
// Regenerate: node --import tsx scripts/generate-gateway-client.ts

export interface AuditOperationsSnapshot {
  available: boolean;
  backend: string;
}

export interface BacktestRequest {
  bars?: number;
  direction?: "long_only" | "long_short";
  embargo_bars?: number;
  fast_max?: number;
  fast_min?: number;
  fast_step?: number;
  fee_bps?: number;
  folds?: number;
  interval?: string;
  label?: string | null;
  notify_chat_id?: string | null;
  slippage_bps?: number;
  slow_max?: number;
  slow_min?: number;
  slow_step?: number;
  strategy?: "ma_cross" | "ema_cross" | "macd_cross" | "donchian" | "donchian_mid" | "breakout_sma" | "rsi_reversion" | "williams_r" | "stochastic" | "momentum" | "roc_trend" | "triple_ma" | "ppo_cross" | "trix_cross" | "rsi_trend" | "price_channel" | "ema_slope" | "bollinger_breakout" | "zscore_reversion" | "atr_breakout" | "keltner_breakout" | "supertrend" | "atr_trailing_stop" | "obv_trend" | "volume_breakout" | "mfi_reversion" | "dema_cross" | "tema_cross" | "zlema_cross" | "hull_trend" | "vwap_trend" | "cci_reversion" | "awesome_cross" | "cmo_trend" | "stoch_rsi_x" | "dpo_reversion" | "bollinger_pctb" | "stddev_channel" | "chaikin_volatility" | "ulcer_filter" | "cmf_trend" | "force_index" | "eom_trend" | "aroon_cross" | "vortex_cross" | "linreg_forecast";
  symbol?: string;
  walk_forward?: boolean;
}

export interface Body_telegram_link_status_telegram_link_status_post {
  probe: string;
}

export interface BookLevel {
  cum_notional: number;
  notional: number;
  price: number;
  size: number;
}

export interface CancelRequest {
  reason?: string;
}

export interface CheckResult {
  detail: string;
  limit?: number | null;
  name: string;
  observed?: number | null;
  passed: boolean;
}

export interface CoherenceAblation {
  description: string;
  gross_total?: string;
  name: string;
  net_total?: string;
  notes?: Array<string>;
  observations?: number;
  untestable?: number;
  violations?: number;
  worth_doing?: number;
}

export interface CoherenceBin {
  high?: string | null;
  label: string;
  low?: string | null;
  mass: string;
  negative?: boolean;
  representative?: string | null;
}

export interface CoherenceBookLevel {
  price: string;
  size: string;
}

export interface CoherenceBookView {
  best_no_ask?: string | null;
  best_no_bid?: string | null;
  best_yes_ask?: string | null;
  best_yes_bid?: string | null;
  depth: string;
  identity_one_plus_spread?: string | null;
  identity_sum?: string | null;
  no_bids?: Array<CoherenceBookLevel>;
  source: string;
  spread?: string | null;
  ticker: string;
  ts_ns?: number | null;
  unquoted_reason?: string | null;
  yes_asks?: Array<CoherenceBookLevel>;
  yes_bids?: Array<CoherenceBookLevel>;
}

export interface CoherenceBooks {
  books?: Array<CoherenceBookView>;
  notes?: Array<string>;
  origin: string;
  state: string;
}

export interface CoherenceBudgetStatus {
  basis: string;
  burst: number;
  default_cost: number;
  published_costs_known: number;
  refusals: number;
  tokens_available: number;
  tokens_per_second: number;
  tokens_spent: number;
}

export interface CoherenceCalibration {
  base_rate?: string | null;
  bias_by_series?: Array<CoherenceSeriesBias>;
  bias_slope?: string | null;
  binning?: string | null;
  bins?: Array<CoherenceReliabilityBin>;
  brier?: string | null;
  composition?: Array<CoherenceCompositionRow>;
  count?: number;
  detail?: string;
  engine: string;
  isotonic_map?: Array<CoherenceMapPoint>;
  median_horizon_s?: number | null;
  reliability?: string | null;
  resolution?: string | null;
  skill?: string | null;
  state: string;
  thin?: boolean;
  uncertainty?: string | null;
}

export interface CoherenceCalibrationHistory {
  notes?: Array<string>;
  points?: Array<CoherenceCalibrationPoint>;
  state: string;
}

export interface CoherenceCalibrationPoint {
  base_rate?: string | null;
  bias_slope?: string | null;
  brier?: string | null;
  detail?: string | null;
  engine: string;
  markets?: number;
  median_horizon_s?: number | null;
  skill?: string | null;
  thin?: boolean;
  ts_ns: number;
  uncertainty?: string | null;
}

export interface CoherenceCertificate {
  because?: string;
  component_id: string;
  engine: string;
  exchange_index: number;
  family?: string;
  gross_edge?: string | null;
  legs?: Array<CoherenceCertificateLeg>;
  margin?: string | null;
  net_edge?: string | null;
  notes?: Array<string>;
  observed_age_s?: number | null;
  priced_out?: boolean;
  proof?: string;
  rows_tested?: number;
  rows_untestable?: number;
  scope?: string;
  series_ticker: string;
  tier?: number;
  tier_note?: string;
  total_fees?: string | null;
  verdict: string;
  worst_case_payoff?: string | null;
  worth_doing?: boolean;
}

export interface CoherenceCertificateLeg {
  direction: string;
  label: string;
  net_fee: string;
  notional: string;
  price: string;
  rebate: string;
  rounding_fee: string;
  size: string;
  ticker: string;
  trade_fee: string;
}

export interface CoherenceCombo {
  band_position?: string | null;
  band_width?: string | null;
  collection_ticker?: string;
  combo_ask?: string | null;
  combo_bid?: string | null;
  combo_mid?: string | null;
  dependence?: string;
  detail?: string;
  independence?: string | null;
  inside_band?: boolean | null;
  label: string;
  legs?: Array<CoherenceComboLeg>;
  lower_bound?: string | null;
  price?: string | null;
  price_basis?: string;
  scope?: string;
  ticker: string;
  upper_bound?: string | null;
  violated_rows?: number;
}

export interface CoherenceComboLeg {
  buy_cost?: string | null;
  label: string;
  opposite_cost?: string | null;
  probability?: string | null;
  side: string;
  ticker: string;
}

export interface CoherenceComboRow {
  because: string;
  bound: string;
  cost?: string | null;
  legs?: Array<CoherenceComboLeg>;
  scope: string;
  slack?: string | null;
  violated?: boolean;
}

export interface CoherenceCombos {
  combos?: Array<CoherenceCombo>;
  notes?: Array<string>;
  observed_age_s?: number | null;
  outside_band?: number;
  quoted?: number;
  rows?: Array<CoherenceComboRow>;
  state: string;
  violations?: number;
}

export interface CoherenceCompositionRow {
  count?: number;
  series_ticker: string;
}

export interface CoherenceDispersion {
  band_fraction?: string | null;
  band_note?: string;
  band_width?: string | null;
  crossed?: number;
  detail?: string;
  highest?: string | null;
  lowest?: string | null;
  market_ticker: string;
  median?: string | null;
  median_width?: string | null;
  quotes?: number;
  spread?: string | null;
  thin?: boolean;
  usable?: number;
}

export interface CoherenceEpisode {
  closed_ts_ns?: number | null;
  component_id: string;
  event_ticker: string;
  exchange_index: number;
  family: string;
  lifetime_s?: string | null;
  opened_ts_ns: number;
  peak_ci?: string | null;
  peak_net_edge_dollars?: string | null;
  samples?: Array<CoherenceEpisodeSample>;
  series_ticker: string;
}

export interface CoherenceEpisodeSample {
  ci?: string | null;
  ts_ns: number;
}

export interface CoherenceEpisodes {
  episodes?: Array<CoherenceEpisode>;
  median_s?: string | null;
  median_withheld_reason?: string | null;
  notes?: Array<string>;
  open_episodes?: number;
  round_trip_s?: string;
  state: string;
  survival?: Array<CoherenceSurvivalPoint>;
  verdict?: string;
}

export interface CoherenceEventView {
  basket_note?: string | null;
  event_ticker: string;
  exchange_index: number;
  liquidity_total?: string | null;
  markets?: Array<CoherenceMarketView>;
  mutually_exclusive: boolean;
  open_interest_total?: string | null;
  series_ticker: string;
  settlement_sources?: Array<string>;
  title: string;
  yes_ask_total?: string | null;
  yes_bid_total?: string | null;
}

export interface CoherenceFeeFill {
  net: string;
  notional: string;
  rebate: string;
  rounding_fee: string;
  trade_fee: string;
}

export interface CoherenceFees {
  balance_precision: string;
  contracts: string;
  fee_aware_threshold?: string | null;
  fills: number;
  minimum_clip?: string | null;
  minimum_clip_note?: string;
  multiplier: string;
  naive_threshold?: string;
  net_as_fraction_of_notional?: string | null;
  notes?: Array<string>;
  per_fill?: Array<CoherenceFeeFill>;
  price: string;
  state: string;
  total?: CoherenceFeeFill | null;
}

export interface CoherenceHostStatus {
  detail?: string | null;
  host: string;
  reachable: boolean;
}

export interface CoherenceIndexPoint {
  ci?: string | null;
  detail?: string | null;
  engine: string;
  event_ticker: string;
  exchange_index: number;
  series_ticker: string;
  ts_ns: number;
}

export interface CoherenceIndexSeries {
  measured?: number;
  notes?: Array<string>;
  points?: Array<CoherenceIndexPoint>;
  series?: Array<string>;
  state: string;
  unmeasurable?: number;
}

export interface CoherenceKelly {
  arbitrage_available?: boolean;
  basket_cost?: string | null;
  cash_fraction?: string | null;
  detail?: string;
  engine: string;
  full_growth_rate?: string | null;
  growth_rate?: string | null;
  reserve_rate?: string | null;
  riskless_growth?: string | null;
  shrinkage?: string;
  staked_fraction?: string | null;
  stakes?: Array<CoherenceStake>;
  state: string;
  worst_case_wealth?: string | null;
}

export interface CoherenceMapPoint {
  calibrated: string;
  quoted: string;
  weight?: number;
}

export interface CoherenceMarketView {
  cap_strike?: string | null;
  depth: string;
  event_ticker: string;
  exchange_index: number;
  floor_strike?: string | null;
  liquidity?: string | null;
  no_ask?: string | null;
  no_bid?: string | null;
  notional_value?: string | null;
  open_interest?: string | null;
  price_grid: string;
  series_ticker: string;
  spread?: string | null;
  strike_kind: string;
  ticker: string;
  unquoted_reason?: string | null;
  volume?: string | null;
  yes_ask?: string | null;
  yes_bid?: string | null;
  yes_sub_title: string;
}

export interface CoherencePendingMinute {
  provisional?: string | null;
  spread?: string | null;
  stations?: number;
  ts_ms: number;
}

export interface CoherenceProbe {
  label: string;
  origin: string;
  strike: string;
  survival: string;
  ticker: string;
}

export interface CoherenceRecorderStatus {
  books_written: number;
  configured: boolean;
  consecutive_failures?: number;
  last_error?: string | null;
  poll_seconds: number;
  polls: number;
  running: boolean;
  seconds_since_last_poll?: number | null;
  series_seen?: Array<string>;
  watchlist: Array<string>;
}

export interface CoherenceReliabilityBin {
  count?: number;
  deviation?: string | null;
  high: string;
  label: string;
  low: string;
  mean_forecast?: string | null;
  outcome_rate?: string | null;
}

export interface CoherenceReplay {
  ablations?: Array<CoherenceAblation>;
  first_ts_ns?: number;
  headline?: string;
  last_ts_ns?: number;
  notes?: Array<string>;
  observations?: number;
  rows?: number;
  span_seconds?: string;
  state: string;
}

export interface CoherenceRfqPanel {
  detail?: string;
  dispersions?: Array<CoherenceDispersion>;
  open_requests?: number;
  state: string;
}

export interface CoherenceSeriesBias {
  series_ticker: string;
  slope: string;
}

export interface CoherenceSettlementFeed {
  city?: string | null;
  config_version?: string;
  contributors_max?: number | null;
  contributors_min?: number | null;
  degraded_samples?: number;
  detail?: string;
  formation_agreed?: number;
  formation_checked?: number;
  formation_detail?: string;
  formation_holds?: boolean;
  latest_value?: string | null;
  pending?: Array<CoherencePendingMinute>;
  quorum_gaps?: number;
  reference_rate_detail?: string;
  reference_rate_state?: string;
  sample_count?: number;
  samples?: Array<CoherenceWeatherSample>;
  spot_minus_window?: string | null;
  state: string;
  stations?: Array<string>;
  units?: string;
  window_average?: string | null;
  window_average_clean?: string | null;
  window_is_assumed?: boolean;
  window_minutes?: number;
}

export interface CoherenceShardStatus {
  description: string;
  exchange_active: boolean;
  exchange_index: number;
  trading_active: boolean;
}

export interface CoherenceShell {
  body?: string;
  command?: string;
  detail?: string;
  entries?: Array<CoherenceShellEntry>;
  exists?: boolean;
  path: string;
  state: string;
}

export interface CoherenceShellEntry {
  detail?: string;
  kind: string;
  name: string;
}

export interface CoherenceStake {
  admitted?: boolean;
  edge: string;
  fraction: string;
  full_fraction: string;
  label: string;
  price: string;
  probability: string;
  ticker: string;
}

export interface CoherenceStatus {
  budget: CoherenceBudgetStatus;
  dry_run?: boolean;
  hosts?: Array<CoherenceHostStatus>;
  notes?: Array<string>;
  recorder: CoherenceRecorderStatus;
  schema_probe?: Record<string, unknown>;
  shards?: Array<CoherenceShardStatus>;
  signing?: Record<string, unknown>;
  solver?: Record<string, unknown>;
  state: string;
  tape?: Record<string, unknown>;
}

export interface CoherenceSurface {
  basis?: string | null;
  bins?: Array<CoherenceBin>;
  detail?: string;
  engine: string;
  event_ticker?: string;
  excess_kurtosis?: string | null;
  mean?: string | null;
  moments_note?: string;
  negative_bins?: Array<string>;
  probes?: Array<CoherenceProbe>;
  skewness?: string | null;
  standard_deviation?: string | null;
  state: string;
  tail_mass_high?: string | null;
  tail_mass_low?: string | null;
  total_mass?: string | null;
  variance?: string | null;
}

export interface CoherenceSurvivalPoint {
  surviving: string;
  t_s: string;
}

export interface CoherenceUniverse {
  categories?: Record<string, string>;
  events?: Array<CoherenceEventView>;
  notes?: Array<string>;
  observed_age_s?: number | null;
  state: string;
  watchlist?: Array<string>;
}

export interface CoherenceWeatherSample {
  contributors?: number;
  status?: string;
  ts_ms: number;
  value: string;
}

export interface DataBackfillRequest {
  from_at: string;
  interval?: "15m" | "1h" | "4h" | "1d";
  symbol: string;
  to_at: string;
}

export interface DataJobAccepted {
  backend: string;
  job_id: string;
  kind: "data.replay" | "data.backfill" | "ml.fit";
  poll: string;
  status: string;
}

export interface DataJobView {
  actor?: string;
  backend?: string;
  error?: string | null;
  finished_at?: string | null;
  job_id: string;
  kind: string;
  message?: string;
  params?: Record<string, unknown>;
  progress?: number;
  started_at?: string | null;
  status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
  submitted_at: string;
  summary?: Record<string, unknown> | null;
}

export interface DataJobsResponse {
  backend: string;
  executor_configured: boolean;
  jobs: Array<DataJobView>;
  observed_at: string;
  restored_from_audit?: number;
  retained_in_process: boolean;
}

export interface DataQualityCapabilityRow {
  capability: string;
  drift: number;
  evaluated: number;
  fatal: number;
  not_evaluated: number;
  passed: number;
  warn: number;
}

export interface DataQualityCounts {
  drift: number;
  evaluated: number;
  fatal: number;
  not_evaluated: number;
  passed: number;
  warn: number;
}

export interface DataQualityEscalationView {
  acknowledged_at: string | null;
  acknowledged_by: string | null;
  channel: "telegram" | "log" | "webhook" | null;
  count: number;
  detail: string;
  evaluated: number | null;
  id: number;
  notified_at: string | null;
  opened_at: string;
  provider: string;
  resolved_at: string | null;
  rule: "fatal_burst" | "fail_rate";
  window_minutes: number;
}

export interface DataQualityFindingView {
  capability: string;
  checks: Array<string>;
  id: number;
  instance: string;
  key: string;
  observed_at: string;
  passed: boolean;
  provider: string;
  severity: "fatal" | "warn" | "drift" | "clean";
  source: "web" | "replay" | "backfill";
  symbol: string | null;
}

export interface DataQualityFindingsResponse {
  findings: Array<DataQualityFindingView>;
  observed_at: string;
  retention_days: number;
  total: number;
  window_minutes: number;
}

export interface DataQualityProviderRow {
  drift: number;
  evaluated: number;
  fail_rate: number | null;
  fatal: number;
  not_evaluated: number;
  passed: number;
  provider: string;
  warn: number;
}

export interface DataQualityView {
  backend: "sqlite" | "postgres";
  by_capability: Array<DataQualityCapabilityRow>;
  by_provider: Array<DataQualityProviderRow>;
  escalations: Array<DataQualityEscalationView>;
  first_observed_at: string | null;
  instances: number;
  last_observed_at: string | null;
  observed_at: string;
  recent: Array<DataQualityFindingView>;
  retention_days: number;
  schema_version?: 1;
  total: DataQualityCounts;
  window_minutes: number;
}

export interface DataReplayRequest {
  bars?: number;
  capability?: "quote" | "bars" | "news" | "fundamentals";
  interval?: "15m" | "1h" | "4h" | "1d";
  symbol: string;
}

export interface DataScheduleView {
  cadence: string;
  error: string | null;
  expression: string;
  id: string;
  kind: "replay" | "backfill";
  last_job_id: string | null;
  last_outcome: string | null;
  last_run_at: string | null;
  next_due_at: string | null;
  valid: boolean;
}

export interface DataSchedulesResponse {
  executor_configured: boolean;
  max_backfill_bars: number;
  observed_at: string;
  schedules: Array<DataScheduleView>;
  tick_seconds: number;
}

export interface DecisionLatencySnapshot {
  core_max_ns?: number | null;
  core_p50_ns?: number | null;
  core_p99_ns?: number | null;
  core_self_test_samples?: number | null;
  engine: "native" | "python";
  max_us?: number | null;
  p50_us?: number | null;
  p999_us?: number | null;
  p99_us?: number | null;
  samples: number;
}

export interface DiffusionAbsorptionResponse {
  backend?: string | null;
  call_curve?: Array<number | null>;
  horizons?: Array<string>;
  observed_at: string;
  reason?: string | null;
  release_curve?: Array<number | null>;
  runs?: Array<DiffusionStageRun>;
  stages?: Array<DiffusionStageSummary>;
  state: "ok" | "unconfigured" | "unavailable" | "unreadable";
  truncated?: boolean;
}

export interface DiffusionCalendar {
  dissent_meetings?: number;
  dissent_votes?: number;
  how: string;
  of?: number;
  verified?: number;
}

export interface DiffusionEvent {
  call_at?: string | null;
  call_at_source?: "vendor" | "fed_seed" | "estimated_offset" | "parsed_release" | "recorded" | null;
  call_offset_min?: number | null;
  eps_actual?: number | null;
  eps_estimate?: number | null;
  first_seen_at: string;
  kind: "earnings" | "fomc" | "macro";
  release_at: string;
  release_at_source: "vendor" | "fed_seed" | "estimated_offset" | "parsed_release" | "recorded";
  release_timing?: string | null;
  revised_count?: number;
  scheduled?: boolean;
  source_ref: string;
  statement_url?: string | null;
  surprise_pct?: number | null;
  symbol?: string | null;
  title: string;
  verified_at?: string | null;
}

export interface DiffusionEventResponse {
  event?: DiffusionEvent | null;
  observed_at: string;
  reason?: string | null;
  state: "ok" | "not_found" | "unconfigured" | "unavailable" | "unreadable";
}

export interface DiffusionEventsResponse {
  backend?: string | null;
  events?: Array<DiffusionEvent>;
  observed_at: string;
  reason?: string | null;
  state: "ok" | "unconfigured" | "unavailable" | "unreadable";
  truncated?: boolean;
}

export interface DiffusionFinding {
  correlation?: number | null;
  n: number;
  name: string;
  note?: string | null;
  question: string;
  shuffled_p?: number | null;
  stage: "release" | "call" | "both";
  t_statistic?: number | null;
  verdict: "holds" | "absent" | "not_assessable";
}

export interface DiffusionFindingsResponse {
  backend?: string | null;
  calendar?: DiffusionCalendar | null;
  findings?: Array<DiffusionFinding>;
  gate?: DiffusionGate | null;
  observed_at: string;
  reason?: string | null;
  state: "ok" | "unconfigured" | "unavailable" | "unreadable";
  study?: DiffusionStudy | null;
}

export interface DiffusionGate {
  fact: string;
  floor: number;
  r_squared?: number | null;
  reason?: string | null;
  samples?: number;
  state: "passed" | "failed" | "not_assessable";
}

export interface DiffusionHorizonCell {
  abnormal_return?: number | null;
  absorbed?: number | null;
  bars?: number | null;
  horizon: string;
  reason?: string | null;
  state: "ok" | "pending" | "uncaptured" | "insufficient" | "unavailable";
}

export interface DiffusionStageRecord {
  at: string;
  note?: string | null;
  source?: "recorded" | "parsed_release";
}

export interface DiffusionStageRun {
  cells?: Array<DiffusionHorizonCell>;
  control_percentile?: number | null;
  controls_used?: number;
  data_hash?: string | null;
  half_life_s?: number | null;
  half_life_state?: string | null;
  half_life_vol?: number | null;
  interval: string;
  market_adjusted?: boolean;
  measured_horizons?: number;
  of_horizons?: number;
  params_version: string;
  run_id: string;
  signal_reason?: string | null;
  signal_state: "ok" | "no_signal" | "insufficient_pre_window" | "unavailable";
  source_ref: string;
  stage: "release" | "call";
  symbol: string;
  t0: string;
  terminal_return?: number | null;
}

export interface DiffusionStageSummary {
  measured?: number;
  median_control_percentile?: number | null;
  median_half_life_s?: number | null;
  no_signal?: number;
  other?: number;
  reason?: string | null;
  stage: "release" | "call";
}

export interface DiffusionStudy {
  centroid_spread?: number | null;
  conditioning: string;
  effective_rank?: number | null;
  events?: number;
  latent_dim: number;
  segment?: string | null;
  skill_baseline_r2?: number | null;
  skill_gain?: number | null;
  skill_meetings?: number;
  skill_shuffled_p?: number | null;
  skill_stage_minutes?: number | null;
  study_id: string;
  verdict?: string | null;
  verdict_reason?: string | null;
}

export interface EscalationAck {
  acknowledged_by: string | null;
  escalation_id: number;
  taken: boolean;
}

export interface ExecutionEstimate {
  fillable: boolean;
  filled_notional: number;
  filled_qty: number;
  levels_consumed: number;
  mid: number | null;
  slippage_bps: number | null;
  venue: string;
  vwap: number | null;
  worst_price: number | null;
}

export interface Fill {
  fee_usd: number;
  notional: number;
  price: number;
  quantity: number;
  simulated?: boolean;
  slippage_bps: number | null;
  venue: string;
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface KillSwitchRequest {
  reason?: string;
  symbol?: string | null;
}

export interface MLFeatureView {
  feature_count: number;
  label: string;
  label_horizon_bars: number;
  spec: Record<string, unknown>;
  spec_hash: string;
}

export interface MLFitRequest {
  bars?: number;
  cost_bps?: number;
  embargo?: number;
  interval?: "15m" | "1h" | "4h" | "1d";
  label_horizon?: number;
  label_kind?: "return" | "direction" | null;
  model?: "ridge" | "logistic";
  n_splits?: number;
  params?: Record<string, unknown>;
  seed?: number;
  symbol?: string;
}

export interface MLFoldView {
  embargo_bars: number;
  fold_index: number;
  oos_max_drawdown?: number | null;
  oos_return?: number | null;
  oos_sharpe?: number | null;
  purge_bars: number;
  test_end: string;
  test_rows: number;
  test_start: string;
  trades?: number | null;
  train_end: string;
  train_rows: number;
  train_start: string;
}

export interface MLRunDetail {
  data_hash: string;
  deflated_sharpe?: number | null;
  engine: string;
  error?: string | null;
  features?: MLFeatureView | null;
  finished_at?: string | null;
  folds?: Array<MLFoldView>;
  git_sha?: string | null;
  id: string;
  interval: string;
  model: string;
  oos_sharpe?: number | null;
  params?: Record<string, unknown>;
  pbo?: number | null;
  seed: number;
  started_at: string;
  status: string;
  symbol: string;
}

export interface MLRunSummary {
  data_hash: string;
  deflated_sharpe?: number | null;
  engine: string;
  error?: string | null;
  finished_at?: string | null;
  git_sha?: string | null;
  id: string;
  interval: string;
  model: string;
  oos_sharpe?: number | null;
  pbo?: number | null;
  seed: number;
  started_at: string;
  status: string;
  symbol: string;
}

export interface MLRunsResponse {
  observed_at: string;
  runs: Array<MLRunSummary>;
  state: "ok" | "unavailable" | "unreadable";
}

export interface MarketDataFeedSnapshot {
  connected: boolean;
  error_present?: boolean;
  reconnects?: number;
  status: "up" | "degraded" | "stale" | "down";
  symbols?: Array<MarketDataSymbolSnapshot>;
  synthetic?: boolean;
  uptime_seconds?: number;
  venue: string;
}

export interface MarketDataSnapshot {
  enabled: boolean;
  feeds?: Array<MarketDataFeedSnapshot>;
  stale_after_seconds: number;
  status: "nominal" | "degraded" | "critical" | "disabled";
  synthetic_active: boolean;
  uptime_seconds?: number;
}

export interface MarketDataSymbolSnapshot {
  age_seconds?: number | null;
  stale?: boolean;
  symbol: string;
  update_rate_hz?: number;
  updates_total?: number;
}

export interface OnCallSnapshot {
  configured: boolean;
  covered: boolean;
  entries: number;
  invalid: number;
  valid: number;
  webhook_configured: boolean;
}

export interface OperationsSnapshot {
  audit: AuditOperationsSnapshot;
  decision_latency?: DecisionLatencySnapshot | null;
  environment: string;
  market_data: MarketDataSnapshot;
  observed_at: string;
  oncall?: OnCallSnapshot | null;
  queue: QueueOperationsSnapshot;
  risk: RiskOperationsSnapshot;
  route_latency: RouteLatencyOperationsSnapshot;
  schema_version?: 1;
  stale_after_seconds: number;
  status: "nominal" | "degraded" | "critical" | "halted";
  supabase?: SupabaseMirrorSnapshot | null;
  telegram: TelegramOperationsSnapshot;
  version: string;
}

export interface OrderAck {
  actor: string;
  at: string;
  order_id: string;
  reason?: string | null;
  status: "WORKING" | "FILLED" | "CANCELLED" | "EXPIRED" | "REJECTED";
}

export interface OrderEvent {
  actor?: string;
  detail?: string;
  event: string;
  fee_usd?: number | null;
  fill_price?: number | null;
  fill_qty?: number | null;
  replaces?: string | null;
  status: "WORKING" | "FILLED" | "CANCELLED" | "EXPIRED" | "REJECTED";
  ts: string;
  venue?: string | null;
}

export interface OrderRequest {
  client_order_id?: string | null;
  limit_price?: number | null;
  notional?: number | null;
  order_type?: "MARKET" | "LIMIT";
  paper_execution?: PaperExecutionReference | null;
  quantity?: number | null;
  side: "BUY" | "SELL";
  strategy?: string;
  symbol: string;
  time_in_force?: "GTC" | "DAY" | "IOC" | null;
}

export interface OrderTimeline {
  events: Array<OrderEvent>;
  order_id: string;
  status: "WORKING" | "FILLED" | "CANCELLED" | "EXPIRED" | "REJECTED";
}

export interface PaperExecutionReference {
  as_of: string;
  asset_class?: "equity";
  currency?: "USD";
  delayed?: boolean;
  price: number;
  source: string;
}

export interface Position {
  avg_price: number;
  mark_price: number | null;
  notional: number;
  quantity: number;
  realized_pnl: number;
  symbol: string;
  unrealized_pnl: number;
}

export interface QueueOperationsSnapshot {
  backend: string;
  broker_configured: boolean;
  broker_transport?: string | null;
  by_status?: Record<string, number>;
  total: number;
  workers: number;
}

export interface ReduceOnlyRequest {
  enabled?: boolean;
  reason?: string;
  symbol?: string | null;
}

export interface ReplaceRequest {
  limit_price?: number | null;
  notional?: number | null;
  quantity?: number | null;
  reason?: string;
}

export interface ResearchAnswer {
  band?: "answer" | "rewrite" | "refuse" | null;
  calls?: Array<ToolCallView>;
  connected?: Array<ResearchGraphNeighbour>;
  corpus_size?: number | null;
  fallback?: boolean;
  generation?: Record<string, unknown> | null;
  matches?: Array<ResearchRagMatch>;
  planner?: string;
  query: string;
  reasons?: Array<string>;
  refusal?: string | null;
  rerank_state?: string | null;
  reranked?: boolean;
  retrievals?: number;
  rewritten_query?: string | null;
  score?: number | null;
  state: "ok" | "refused" | "unavailable" | "embed_failed";
}

export interface ResearchBoundRefusal {
  correlation_id?: string | null;
  query: string;
  reason: string;
  retry_after_s?: number | null;
  route: string;
  spend?: Record<string, unknown> | null;
  state: "rate_limited" | "spend_capped" | "scope_unavailable";
}

export interface ResearchGraphNeighbour {
  arrived_by: string;
  depth: number;
  evidence?: string | null;
  id: string;
  kind: string;
  occurred_at: string;
  source_ref: string;
  strategy?: string | null;
  symbol?: string | null;
  title: string;
}

export interface ResearchGraphResponse {
  connected: Array<ResearchGraphNeighbour>;
  state: "ok" | "unavailable";
}

export interface ResearchRagAnomalyMatch {
  kind: string;
  occurred_at: string;
  similarity: number;
  title: string;
}

export interface ResearchRagEmbedRequest {
  texts: Array<string>;
}

export interface ResearchRagEmbedResponse {
  dimensions?: number | null;
  embeddings?: Array<Array<number>>;
  model?: string | null;
  state: "ok" | "unavailable";
}

export interface ResearchRagMatch {
  bm25_rank?: number | null;
  body: string;
  id: string;
  kind: string;
  lexical_rank?: number | null;
  metrics?: Record<string, unknown>;
  occurred_at: string;
  rerank_score?: number | null;
  similarity: number;
  source_ref: string;
  strategy?: string | null;
  symbol?: string | null;
  title: string;
  vector_rank?: number | null;
}

export interface ResearchRagSearchRequest {
  kind?: "backtest_run" | "chart" | "execution_summary" | "ml_run" | "risk_incident" | null;
  match_count?: number;
  query: string;
}

export interface ResearchRagSearchResponse {
  bm25?: Record<string, unknown> | null;
  corpus_size?: number | null;
  correlation_id?: string | null;
  image?: Record<string, unknown> | null;
  matches?: Array<ResearchRagMatch>;
  rerank_state?: string | null;
  reranked?: boolean;
  state: "ok" | "unavailable" | "embed_failed";
}

export interface ResearchRagStatus {
  configured: boolean;
  dropped: number;
  failed: number;
  indexed: number;
  last_anomaly_at?: string | null;
  last_anomaly_matches?: Array<ResearchRagAnomalyMatch>;
  pending_embeddings: number;
  queued: number;
  running: boolean;
}

export interface RiskDecision {
  accepted: boolean;
  checks: Array<CheckResult>;
  client_order_id: string | null;
  fill?: Fill | null;
  latency_ms?: number;
  notional: number | null;
  order_id: string;
  quantity: number | null;
  reason?: string | null;
  rejected_by?: Array<string>;
  side: "BUY" | "SELL";
  status?: "WORKING" | "FILLED" | "CANCELLED" | "EXPIRED" | "REJECTED";
  symbol: string;
  time_in_force?: "GTC" | "DAY" | "IOC" | null;
  timestamp: string;
}

export interface RiskOperationsSnapshot {
  daily_drawdown_pct: number;
  drawdown_budget_used_pct: number;
  equity: number;
  gross_exposure: number;
  halted_symbols?: Array<string>;
  kill_switch_active: boolean;
  orders_accepted_total: number;
  orders_last_second: number;
  orders_rejected_total: number;
  reduce_only: boolean;
  status: "nominal" | "reduce_only" | "halted";
  working_orders: number;
}

export interface RiskState {
  carried_realized_pnl?: number;
  daily_drawdown_pct: number;
  daily_pnl: number;
  drawdown_budget_used_pct: number;
  equity: number;
  gross_exposure: number;
  halted_symbols: Array<string>;
  kill_reason: string | null;
  kill_switch_active: boolean;
  killed_at: string | null;
  killed_by: string | null;
  limits: Record<string, number>;
  orders_accepted: number;
  orders_last_second: number;
  orders_rejected: number;
  positions: Array<Position>;
  realized_pnl: number;
  reduce_only?: boolean;
  reduce_only_source?: "threshold" | "operator" | "off";
  reduce_only_threshold?: number;
  session_date: string;
  start_of_day_equity: number;
  unrealized_pnl: number;
  working_notional?: number;
  working_orders?: number;
}

export interface RouteLatencyOperationsSnapshot {
  routes?: Array<RouteLatencySnapshot>;
  window_seconds: number;
}

export interface RouteLatencySnapshot {
  errors_total: number;
  p50_ms: number;
  p95_ms: number;
  p99_ms: number;
  route: string;
  samples: number;
}

export interface RoutingLeg {
  notional: number;
  qty: number;
  share_pct: number;
  venue: string;
  vwap: number;
}

export interface SupabaseMirrorSnapshot {
  configured: boolean;
  dropped: number;
  failed: number;
  last_error_kind?: string | null;
  queued: number;
  running: boolean;
  written: number;
}

export interface TCAReport {
  best_single_venue: string | null;
  consolidated_mid: number | null;
  generated_at: string;
  per_venue: Array<ExecutionEstimate>;
  saving_vs_worst_bps: number | null;
  saving_vs_worst_usd: number | null;
  side: "BUY" | "SELL";
  smart_route: Array<RoutingLeg>;
  smart_route_slippage_bps: number | null;
  smart_route_vwap: number | null;
  symbol: string;
  synthetic?: boolean;
  target_notional: number;
  venues_online: Array<string>;
}

export interface TelegramOperationsSnapshot {
  alerts_sent: number;
  enabled: boolean;
  last_error_kind?: "transport" | "conflict" | "api" | null;
  last_error_present: boolean;
  mode: string;
  status: "running" | "starting" | "degraded" | "disabled";
  updates_handled: number;
  uptime_seconds: number;
}

export interface ToolCallView {
  detail?: string | null;
  reason: string;
  rows: number;
  state: string;
  tool: string;
}

export interface ValidationError {
  ctx?: Record<string, unknown>;
  input?: unknown;
  loc: Array<string | number>;
  msg: string;
  type: string;
}

export interface VenueBook {
  asks?: Array<BookLevel>;
  best_ask?: number | null;
  best_bid?: number | null;
  bids?: Array<BookLevel>;
  connected: boolean;
  depth_usd_ask?: number;
  depth_usd_bid?: number;
  imbalance?: number | null;
  last_update?: string | null;
  latency_ms?: number | null;
  mid?: number | null;
  spread_bps?: number | null;
  stale: boolean;
  symbol: string;
  synthetic?: boolean;
  venue: string;
}

export interface WebContractCheck {
  check: string;
  message?: string;
  severity: "fatal" | "warn" | "drift";
}

export interface WebContractFinding {
  capability: string;
  checks?: Array<WebContractCheck>;
  drift?: number;
  fatal?: number;
  key?: string;
  not_evaluated?: number;
  observed_at: number;
  passed: boolean;
  provider: string;
  seq: number;
  symbol?: string | null;
  warn?: number;
}

export interface WebLatencyBatch {
  key: string;
  samples?: Array<WebLatencySample>;
}

export interface WebLatencyKeyView {
  key: string;
  samples?: Array<WebLatencySample>;
}

export interface WebLatencySample {
  ms: number;
  ok: boolean;
  ts: number;
}

export interface WebOutageCommand {
  expires_at: number;
  note?: string;
  provider: string;
}

export interface WebOutageView {
  expires_at: number;
  note: string;
  provider: string;
}

export interface WebQuotaReset {
  provider: string;
  window: string;
}

export interface WebQuotaSpend {
  provider: string;
  spent: number;
  window: string;
}

export interface WebQuotaView {
  provider: string;
  spent: number;
  window: string;
}

export interface WebStateSyncRequest {
  findings?: Array<WebContractFinding>;
  instance: string;
  latency?: Array<WebLatencyBatch>;
  outages_cleared?: Array<string>;
  outages_set?: Array<WebOutageCommand>;
  quota?: Array<WebQuotaSpend>;
  quota_reset?: Array<WebQuotaReset>;
  schema_version?: 1;
}

export interface WebStateView {
  data_quality: DataQualityView;
  instances: Array<string>;
  latency: Array<WebLatencyKeyView>;
  observed_at: string;
  outages: Array<WebOutageView>;
  quota: Array<WebQuotaView>;
  schema_version?: 1;
  window_seconds: number;
}

export interface WorkItemConflict {
  current: WorkItemView;
  error: "version_conflict";
}

export interface WorkItemCreate {
  area?: string;
  kind: "request" | "ticket" | "bug";
  owner?: string;
  priority: "P0" | "P1" | "P2" | "P3";
  sla_hours?: number | null;
  summary?: string;
  title: string;
}

export interface WorkItemPatch {
  area?: string | null;
  owner?: string | null;
  priority?: "P0" | "P1" | "P2" | "P3" | null;
  status?: "intake" | "ready" | "progress" | "resolved" | null;
  summary?: string | null;
  title?: string | null;
  version: number;
}

export interface WorkItemView {
  area: string;
  created_by: string;
  id: string;
  kind: "request" | "ticket" | "bug";
  opened_at: number;
  owner: string;
  priority: "P0" | "P1" | "P2" | "P3";
  resolved_at: number | null;
  sla_due_at: number | null;
  status: "intake" | "ready" | "progress" | "resolved";
  summary: string;
  title: string;
  updated_at: number;
  updated_by: string;
  version: number;
}

export interface WorkItemsResponse {
  backend: "sqlite" | "postgres";
  count: number;
  items: Array<WorkItemView>;
  observed_at: string;
  seeded: number;
}

export interface WorkingOrder {
  accepted_at: string;
  age_seconds: number;
  client_order_id?: string | null;
  distance_bps?: number | null;
  expires_at?: string | null;
  limit_price: number;
  mark_price?: number | null;
  notional: number;
  order_id: string;
  order_type: "MARKET" | "LIMIT";
  quantity: number;
  side: "BUY" | "SELL";
  source: string;
  status: "WORKING" | "FILLED" | "CANCELLED" | "EXPIRED" | "REJECTED";
  strategy: string;
  symbol: string;
  time_in_force: "GTC" | "DAY" | "IOC";
}

/** Request/response bindings keyed by "METHOD /path". */
export interface GatewayOperations {
  "GET /api/audit/backtests": { response: Array<Record<string, unknown>> };
  "GET /api/audit/events": { response: Array<Record<string, unknown>> };
  "GET /api/audit/orders": { response: Array<Record<string, unknown>> };
  "GET /api/audit/stats": { response: Record<string, unknown> };
  "POST /api/backtest": { request: BacktestRequest; response: Record<string, unknown> };
  "GET /api/book/{symbol}": { response: Array<VenueBook> };
  "GET /api/coherence/books": { response: CoherenceBooks };
  "GET /api/coherence/calibration": { response: CoherenceCalibration };
  "GET /api/coherence/calibration/history": { response: CoherenceCalibrationHistory };
  "GET /api/coherence/certify": { response: CoherenceCertificate };
  "GET /api/coherence/combos": { response: CoherenceCombos };
  "GET /api/coherence/episodes": { response: CoherenceEpisodes };
  "GET /api/coherence/fees": { response: CoherenceFees };
  "GET /api/coherence/index": { response: CoherenceIndexSeries };
  "GET /api/coherence/replay": { response: CoherenceReplay };
  "GET /api/coherence/rfq": { response: CoherenceRfqPanel };
  "GET /api/coherence/settlement": { response: CoherenceSettlementFeed };
  "GET /api/coherence/shell": { response: CoherenceShell };
  "GET /api/coherence/stake": { response: CoherenceKelly };
  "GET /api/coherence/status": { response: CoherenceStatus };
  "GET /api/coherence/surface": { response: CoherenceSurface };
  "GET /api/coherence/universe": { response: CoherenceUniverse };
  "GET /api/config": { response: Record<string, unknown> };
  "POST /api/data-quality/escalations/{escalation_id}/ack": { response: EscalationAck };
  "GET /api/data-quality/findings": { response: DataQualityFindingsResponse };
  "GET /api/data-quality/view": { response: DataQualityView };
  "POST /api/data/backfill": { request: DataBackfillRequest; response: DataJobAccepted };
  "GET /api/data/jobs": { response: DataJobsResponse };
  "POST /api/data/replay": { request: DataReplayRequest; response: DataJobAccepted };
  "GET /api/data/schedules": { response: DataSchedulesResponse };
  "GET /api/data/work-items": { response: WorkItemsResponse };
  "POST /api/data/work-items": { request: WorkItemCreate; response: WorkItemView };
  "DELETE /api/data/work-items/{item_id}": { response: WorkItemView };
  "PATCH /api/data/work-items/{item_id}": { request: WorkItemPatch; response: WorkItemView };
  "GET /api/jobs": { response: Record<string, unknown> };
  "GET /api/jobs/{job_id}": { response: Record<string, unknown> };
  "GET /api/ops/snapshot": { response: OperationsSnapshot };
  "POST /api/ops/web-state/sync": { request: WebStateSyncRequest; response: WebStateView };
  "GET /api/orders": { response: Array<WorkingOrder> };
  "POST /api/orders": { request: OrderRequest; response: RiskDecision };
  "GET /api/orders/{order_id}": { response: OrderTimeline };
  "POST /api/orders/{order_id}/cancel": { request: CancelRequest; response: OrderAck };
  "POST /api/orders/{order_id}/replace": { request: ReplaceRequest; response: RiskDecision };
  "GET /api/portfolio": { response: Record<string, unknown> };
  "GET /api/portfolio/history": { response: Record<string, unknown> };
  "GET /api/research/diffusion/absorption": { response: DiffusionAbsorptionResponse };
  "GET /api/research/diffusion/events": { response: DiffusionEventsResponse };
  "POST /api/research/diffusion/events/{source_ref}/stage": { request: DiffusionStageRecord; response: DiffusionEventResponse };
  "GET /api/research/diffusion/findings": { response: DiffusionFindingsResponse };
  "GET /api/research/graph/centrality": { response: Record<string, unknown> };
  "GET /api/research/graph/communities": { response: Record<string, unknown> };
  "GET /api/research/graph/{document_id}": { response: ResearchGraphResponse };
  "POST /api/research/ml/fit": { request: MLFitRequest; response: DataJobAccepted };
  "GET /api/research/ml/runs": { response: MLRunsResponse };
  "GET /api/research/ml/runs/{run_id}": { response: MLRunDetail };
  "GET /api/research/openbb/bars": { response: Record<string, unknown> };
  "GET /api/research/openbb/fundamentals": { response: Record<string, unknown> };
  "GET /api/research/openbb/health": { response: Record<string, unknown> };
  "GET /api/research/openbb/news": { response: Record<string, unknown> };
  "GET /api/research/openbb/quote": { response: Record<string, unknown> };
  "POST /api/research/rag/ask": { request: ResearchRagSearchRequest; response: ResearchAnswer };
  "POST /api/research/rag/embed": { request: ResearchRagEmbedRequest; response: ResearchRagEmbedResponse };
  "POST /api/research/rag/search": { request: ResearchRagSearchRequest; response: ResearchRagSearchResponse };
  "GET /api/research/rag/status": { response: ResearchRagStatus };
  "POST /api/risk/kill": { request: KillSwitchRequest; response: Record<string, unknown> };
  "GET /api/risk/limits": { response: Record<string, number> };
  "POST /api/risk/reduce-only": { request: ReduceOnlyRequest; response: Record<string, unknown> };
  "POST /api/risk/reset": { response: Record<string, unknown> };
  "POST /api/risk/resume": { request: KillSwitchRequest; response: Record<string, unknown> };
  "GET /api/risk/state": { response: RiskState };
  "GET /api/stream/desk": { response: unknown };
  "GET /api/tca/{symbol}": { response: TCAReport };
  "GET /health": { response: Record<string, unknown> };
  "GET /metrics": { response: unknown };
  "GET /telegram/health": { response: Record<string, unknown> };
  "POST /telegram/link/status": { request: Body_telegram_link_status_telegram_link_status_post; response: Record<string, unknown> };
  "POST /telegram/webhook": { response: Record<string, boolean> };
}

/** Every path the committed contract publishes. */
export const GATEWAY_CONTRACT_PATHS = [
  "/api/audit/backtests",
  "/api/audit/events",
  "/api/audit/orders",
  "/api/audit/stats",
  "/api/backtest",
  "/api/book/{symbol}",
  "/api/coherence/books",
  "/api/coherence/calibration",
  "/api/coherence/calibration/history",
  "/api/coherence/certify",
  "/api/coherence/combos",
  "/api/coherence/episodes",
  "/api/coherence/fees",
  "/api/coherence/index",
  "/api/coherence/replay",
  "/api/coherence/rfq",
  "/api/coherence/settlement",
  "/api/coherence/shell",
  "/api/coherence/stake",
  "/api/coherence/status",
  "/api/coherence/surface",
  "/api/coherence/universe",
  "/api/config",
  "/api/data-quality/escalations/{escalation_id}/ack",
  "/api/data-quality/findings",
  "/api/data-quality/view",
  "/api/data/backfill",
  "/api/data/jobs",
  "/api/data/replay",
  "/api/data/schedules",
  "/api/data/work-items",
  "/api/data/work-items/{item_id}",
  "/api/jobs",
  "/api/jobs/{job_id}",
  "/api/ops/snapshot",
  "/api/ops/web-state/sync",
  "/api/orders",
  "/api/orders/{order_id}",
  "/api/orders/{order_id}/cancel",
  "/api/orders/{order_id}/replace",
  "/api/portfolio",
  "/api/portfolio/history",
  "/api/research/diffusion/absorption",
  "/api/research/diffusion/events",
  "/api/research/diffusion/events/{source_ref}/stage",
  "/api/research/diffusion/findings",
  "/api/research/graph/centrality",
  "/api/research/graph/communities",
  "/api/research/graph/{document_id}",
  "/api/research/ml/fit",
  "/api/research/ml/runs",
  "/api/research/ml/runs/{run_id}",
  "/api/research/openbb/bars",
  "/api/research/openbb/fundamentals",
  "/api/research/openbb/health",
  "/api/research/openbb/news",
  "/api/research/openbb/quote",
  "/api/research/rag/ask",
  "/api/research/rag/embed",
  "/api/research/rag/search",
  "/api/research/rag/status",
  "/api/risk/kill",
  "/api/risk/limits",
  "/api/risk/reduce-only",
  "/api/risk/reset",
  "/api/risk/resume",
  "/api/risk/state",
  "/api/stream/desk",
  "/api/tca/{symbol}",
  "/health",
  "/metrics",
  "/telegram/health",
  "/telegram/link/status",
  "/telegram/webhook",
] as const;

export type GatewayContractPath = (typeof GATEWAY_CONTRACT_PATHS)[number];
