/**
 * Generated by `scripts/refresh-test-counts.mjs`. Do not edit by hand — that
 * is precisely what went wrong three times before this file existed.
 *
 * Each figure is what its runner printed on 2026-08-31. Re-run the script after
 * adding tests; nothing regenerates these automatically, because running three
 * suites inside `next build` would make every deploy pay for them.
 */

export const TEST_COUNTS = {
  generatedOn: "2026-08-31",
  gateway: { total: 3409, passed: 3408, skipped: 1 },
  web: { total: 6773, suites: 1448 },
  service: { total: 24 },
} as const;
