/**
 * Generated by `scripts/refresh-test-counts.mjs`. Do not edit by hand — that
 * is precisely what went wrong three times before this file existed.
 *
 * Each figure is what its runner printed on 2026-08-25. Re-run the script after
 * adding tests; nothing regenerates these automatically, because running three
 * suites inside `next build` would make every deploy pay for them.
 */

export const TEST_COUNTS = {
  generatedOn: "2026-08-25",
  gateway: { total: 3066, passed: 3064, skipped: 2 },
  web: { total: 5104, suites: 1077 },
  service: { total: 24 },
} as const;
