/**
 * Generates lib/mc-parity-reference.generated.ts — the committed byte-exact
 * reference for the cross-engine Monte Carlo parity check.
 *
 * Run manually and commit the output whenever the simulation intentionally
 * changes:
 *   node --import tsx scripts/generate-mc-parity.ts
 *
 * The server (per instance) and the Developer console (per visiting browser)
 * both recompute the same fixed simulation and compare against this file;
 * `tests/mc-parity.test.ts` fails the suite the moment the algorithm drifts
 * from what is committed here.
 */

import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { computeMcParityJson, MC_PARITY_HORIZON_BARS, MC_PARITY_PATHS } from "../lib/mc-parity";

const json = computeMcParityJson();
const sha256 = createHash("sha256").update(json, "utf8").digest("hex");

const outPath = fileURLToPath(new URL("../lib/mc-parity-reference.generated.ts", import.meta.url));
const banner = `// Generated by scripts/generate-mc-parity.ts — do not edit by hand.
// ${MC_PARITY_PATHS} paths × ${MC_PARITY_HORIZON_BARS} bars; see lib/mc-parity.ts for the fixture.
`;
writeFileSync(
  outPath,
  `${banner}export const MC_PARITY_REFERENCE_JSON = ${JSON.stringify(json)};
export const MC_PARITY_REFERENCE_SHA256 = "${sha256}";
`,
);
console.log(`wrote lib/mc-parity-reference.generated.ts (${json.length} bytes, sha256 ${sha256.slice(0, 12)}…)`);
