-- AlphaEngine — Oracle Autonomous Database 23ai schema.
--
-- Run as ADMIN (or as the owner created by 03_app_user.sql):
--   sqlplus ADMIN/"$ORACLE_PASSWORD"@"$ORACLE_CONN_STRING" @oracle/01_schema.sql
--
-- Deviations from the master blueprint, each with its reason. The blueprint's
-- Phase 4 listing does not run as written; these are the corrections.
--
--  * VECTOR(384), not VECTOR(1536). The only embedding source in this repo is
--    supabase/functions/embed-research, which runs gte-small at 384 dimensions
--    — matching `extensions.vector(384)` in the pgvector migration and
--    `match_research_documents`. At 1536 this index could never be populated
--    from the existing corpus and the two backends would be incomparable.
--    web/tests/oracle-contract.test.ts asserts the two numbers are equal.
--
--  * The HNSW index is created SEPARATELY and is allowed to fail. An in-memory
--    neighbour graph needs the vector memory pool (VECTOR_MEMORY_SIZE), which
--    is not enabled by default and is not always settable on an Always Free
--    instance. Exact search over a corpus this size is milliseconds, so a
--    missing index is a performance note, not an outage — see 01b below.
--
--  * `embedding` is NULLABLE and a row without one is `embedding_status =
--    'pending'`. Never write a zero vector as a placeholder: it is equidistant
--    from every query and would surface as "similar" to anything asked. Same
--    rule the pgvector migration states for the same reason.
--
--  * `data_hash` ties a document to the exact bars its run saw, so evidence
--    found by similarity can be traced back to the dataset that produced it.

-- ---------------------------------------------------------------------------
-- Research corpus
-- ---------------------------------------------------------------------------

CREATE TABLE strategy_research_rag (
  research_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind             VARCHAR2(32)  NOT NULL,
  source_ref       VARCHAR2(200) NOT NULL,
  strategy_name    VARCHAR2(100),
  symbol           VARCHAR2(32),
  data_hash        VARCHAR2(64),
  title            VARCHAR2(300) NOT NULL,
  -- The EXACT text that was embedded. A later change to the card renderer must
  -- not silently invalidate every stored vector with no way to detect it.
  body             CLOB          NOT NULL,
  metrics          CLOB CHECK (metrics IS JSON),
  embedding        VECTOR(384, FLOAT32),
  embedding_status VARCHAR2(16)  DEFAULT 'pending' NOT NULL,
  occurred_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT rag_kind_ck CHECK (kind IN ('backtest_run', 'execution_summary', 'risk_incident')),
  CONSTRAINT rag_status_ck CHECK (embedding_status IN ('pending', 'ready', 'failed')),
  -- A 'ready' row without a vector is the state that silently breaks search.
  CONSTRAINT rag_ready_has_vector_ck CHECK (embedding_status <> 'ready' OR embedding IS NOT NULL),
  CONSTRAINT rag_source_uk UNIQUE (kind, source_ref)
);

CREATE INDEX strategy_research_rag_kind_ix ON strategy_research_rag (kind, occurred_at DESC);

-- ---------------------------------------------------------------------------
-- 01b. Vector index — run separately, tolerate failure
-- ---------------------------------------------------------------------------
-- ORA-51961 / ORA-00439 here means the vector memory pool is unavailable on
-- this instance. Queries still work: VECTOR_DISTANCE falls back to an exact
-- scan. Do not "fix" it by dropping the accuracy target — a wrong neighbour is
-- worse than a slow one for evidence retrieval.

DECLARE
  index_unavailable EXCEPTION;
  PRAGMA EXCEPTION_INIT(index_unavailable, -51961);
BEGIN
  EXECUTE IMMEDIATE '
    CREATE VECTOR INDEX idx_strategy_hnsw ON strategy_research_rag (embedding)
    ORGANIZATION INMEMORY NEIGHBOR GRAPH
    DISTANCE COSINE
    WITH TARGET ACCURACY 98';
  DBMS_OUTPUT.PUT_LINE('HNSW vector index created.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(
      'HNSW index unavailable (' || SQLCODE || '); exact search will be used. '
      || 'Enable VECTOR_MEMORY_SIZE to index.');
END;
/
