-- AlphaEngine — Oracle Autonomous Database 23ai schema.
--
-- Applied by `Part2_Infrastructure/tools/apply_oracle_schema.py`, which is what
-- the "Apply database schema" workflow runs. By hand:
--   sqlplus ADMIN/"$ORACLE_PASSWORD"@"$ORACLE_CONN_STRING" @oracle/01_schema.sql
--
-- EVERY STATEMENT IS RE-RUNNABLE. Oracle has no `CREATE TABLE IF NOT EXISTS`,
-- so each DDL is wrapped in a block that swallows only its own "already exists"
-- code and re-raises everything else. A schema script you cannot run twice is a
-- script nobody dares run once, and it makes the apply job a one-shot that
-- fails on every subsequent deploy.
--
-- Statements are terminated by `/` on its own line — the sqlplus convention,
-- and what lets the applier split the file unambiguously.
--
-- ─── DEVIATIONS FROM THE MASTER BLUEPRINT, with reasons ──────────────────────
--
--  * VECTOR(384), not VECTOR(1536). The only embedding source in this repo is
--    supabase/functions/embed-research, running gte-small at 384 dimensions —
--    matching `extensions.vector(384)` in the pgvector migration. At 1536 this
--    index could never be populated from the existing corpus, and a query
--    embedded by a different model returns confident, meaningless neighbours:
--    a failure that looks exactly like success.
--    web/tests/oracle-contract.test.ts asserts the three numbers agree.
--
--  * The HNSW index is created separately and is allowed to fail. An in-memory
--    neighbour graph needs the vector memory pool (VECTOR_MEMORY_SIZE), which
--    is not enabled by default and is not always settable on an Always Free
--    instance. Exact search over a corpus this size is milliseconds, so a
--    missing index is a performance note, not an outage.
--
--  * `embedding` is NULLABLE and a row without one is `embedding_status =
--    'pending'`. Never write a zero vector as a placeholder: it is equidistant
--    from every query and would surface as "similar" to anything asked. The
--    pgvector migration states the same rule for the same reason.

-- ---------------------------------------------------------------------------
-- Research corpus
-- ---------------------------------------------------------------------------

DECLARE
  already_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(already_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE strategy_research_rag (
      research_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      kind             VARCHAR2(32)  NOT NULL,
      source_ref       VARCHAR2(200) NOT NULL,
      strategy_name    VARCHAR2(100),
      symbol           VARCHAR2(32),
      data_hash        VARCHAR2(64),
      title            VARCHAR2(300) NOT NULL,
      body             CLOB          NOT NULL,
      metrics          CLOB CHECK (metrics IS JSON),
      embedding        VECTOR(384, FLOAT32),
      embedding_status VARCHAR2(16)  DEFAULT 'pending' NOT NULL,
      occurred_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
      created_at       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT rag_kind_ck CHECK (kind IN ('backtest_run', 'execution_summary', 'risk_incident')),
      CONSTRAINT rag_status_ck CHECK (embedding_status IN ('pending', 'ready', 'failed')),
      CONSTRAINT rag_ready_has_vector_ck CHECK (embedding_status <> 'ready' OR embedding IS NOT NULL),
      CONSTRAINT rag_source_uk UNIQUE (kind, source_ref)
    )]';
  DBMS_OUTPUT.PUT_LINE('created strategy_research_rag');
EXCEPTION
  WHEN already_exists THEN DBMS_OUTPUT.PUT_LINE('strategy_research_rag already exists');
END;
/

DECLARE
  already_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(already_exists, -955);
BEGIN
  EXECUTE IMMEDIATE
    'CREATE INDEX strategy_research_rag_kind_ix ON strategy_research_rag (kind, occurred_at DESC)';
  DBMS_OUTPUT.PUT_LINE('created strategy_research_rag_kind_ix');
EXCEPTION
  WHEN already_exists THEN DBMS_OUTPUT.PUT_LINE('strategy_research_rag_kind_ix already exists');
END;
/

-- ---------------------------------------------------------------------------
-- Vector index — tolerate an instance without the vector memory pool
-- ---------------------------------------------------------------------------
-- ORA-51961 and friends mean the pool is unavailable here. Queries still work:
-- VECTOR_DISTANCE falls back to an exact scan. Do not "fix" it by lowering the
-- accuracy target — a wrong neighbour is worse than a slow one for evidence
-- retrieval.

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE VECTOR INDEX idx_strategy_hnsw ON strategy_research_rag (embedding)
    ORGANIZATION INMEMORY NEIGHBOR GRAPH
    DISTANCE COSINE
    WITH TARGET ACCURACY 98]';
  DBMS_OUTPUT.PUT_LINE('created idx_strategy_hnsw');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      DBMS_OUTPUT.PUT_LINE('idx_strategy_hnsw already exists');
    ELSE
      DBMS_OUTPUT.PUT_LINE(
        'HNSW index unavailable (' || SQLCODE || '); exact search will be used. '
        || 'Enable VECTOR_MEMORY_SIZE to index.');
    END IF;
END;
/
