/**
 * Every table on the two engine tabs, declared: what it is, what each column
 * is headed, what kind of cell sits under it, and how it is framed.
 *
 * Twenty-two `<table>` elements in nineteen files, measured on 2026-08-26 by
 * reading every `<table` under `components/coherence/` (surface included,
 * Diffusion excluded — it has its own contract). `engine-data-contract.test.ts`
 * derives the same list by scanning, so a table added without a row here is
 * red, and a row here for a table that has gone is red too.
 *
 * WHY DECLARE RATHER THAN INFER. A header-text match cannot tell a row label
 * from a paraphrase, a count column from an identifier, or a marks column from
 * a cell that happens to hold a glyph — `copy-audit-engines` records four
 * columns a first pass flagged wrongly for exactly that reason. So each column
 * says what it is, and the test holds the markup to the declaration.
 *
 *   kind "num"   — a quantity: `.num` on the `<th>` and every `<td>`, right-aligned
 *                  in tabular figures, dash (never blank, never 0) when null.
 *   kind "text"  — words, left. An identifier (a ticker, a shard index, a fill
 *                  ordinal, a band label) is text even when it is digits: it
 *                  names a row, it is not measured.
 *   kind "marks" — the house vocabulary ● ▲ ✕ ○ ◌ ✓ →, always mark + word.
 *
 *   rowKey "quantity" — the ONE table whose row header is itself a number
 *                       (`CombosBounds`' bound) and carries `.num`.
 */

export type Kind = "text" | "num" | "marks";

export interface TableDecl {
  /** Web-relative path. */
  file: string;
  /** Which `<table>` in the file, when it holds more than one. */
  nth?: number;
  tab: "coherence" | "markets" | "both";
  what: string;
  /** [header label, a token the cell beneath must contain, what kind of cell]. */
  columns: ReadonlyArray<readonly [label: string, token: string, kind: Kind]>;
  rowKey: "identifier" | "quantity";
  /** Whether the table sits inside a `<details>` in its own file. */
  wrapper: "open" | "folded";
  /** A key/value table with no `<thead>`: its row headers are its only headers. */
  headless?: true;
  /** Header cells generated by a `.map` — the count cannot be compared with the cells. */
  generated?: true;
  /** Rows rendered by a child component; the cell check reads nothing here. */
  cellsElsewhere?: true;
  /** Inside a bordered card — the frame is the card's, and the table drops its own. */
  nested?: true;
  /** A `<details>` inside a cell (DispersionTable's per-row fold). */
  cellFold?: true;
  /** The total row, and the one spelling it is allowed. */
  total?: "tfoot";
}

export const TABLES: readonly TableDecl[] = [
  // ------------------------------------------------------------- Proofs --
  {
    file: "components/coherence/CertificateViews.tsx", nth: 0, tab: "coherence",
    what: "the six quantities the certificate decides on",
    columns: [["Quantity", "row.label", "text"], ["Value", "row.of(data)", "num"], ["What it decides", "row.decides", "text"]],
    rowKey: "identifier", wrapper: "folded",
  },
  {
    file: "components/coherence/CertificateViews.tsx", nth: 1, tab: "coherence",
    what: "what the solver concluded",
    // A reading table's value cell is a figure by role even when the row holds
    // a word: the column right-aligns in the numerals face. Red until slice 12.
    columns: [["Reading", "row.label", "text"], ["Value", "row.of(data)", "num"]],
    rowKey: "identifier", wrapper: "open",
  },
  {
    file: "components/coherence/CombosViews.tsx", nth: 0, tab: "coherence",
    what: "a parlay's legs",
    columns: [
      ["Leg", "leg.ticker", "text"], ["Must land", "leg.side", "text"], ["Implied p", "leg.probability", "num"],
      ["Buy cost", "leg.buy_cost", "num"], ["Opposite cost", "leg.opposite_cost", "num"],
    ],
    rowKey: "identifier", wrapper: "folded",
  },
  {
    file: "components/coherence/CombosViews.tsx", nth: 1, tab: "coherence",
    what: "every listed parlay against its band",
    columns: [
      ["Parlay", "combo.ticker", "text"], ["Legs", "combo.legs.length", "num"], ["Lower bound", "combo.lower_bound", "num"],
      ["Upper bound", "combo.upper_bound", "num"], ["Band width", "combo.band_width", "num"], ["Price", "combo.price", "num"],
      ["In band", "position", "num"],
    ],
    rowKey: "identifier", wrapper: "open",
  },
  {
    file: "components/coherence/CombosBounds.tsx", nth: 0, tab: "coherence",
    what: "the legs a bound is built from",
    columns: [["Leg", "leg.label", "text"], ["Direction", "leg.buy_cost", "text"], ["Side", "leg.side", "text"], ["Cost", "leg.buy_cost", "num"]],
    rowKey: "identifier", wrapper: "open",
  },
  {
    file: "components/coherence/CombosBounds.tsx", nth: 1, tab: "coherence",
    what: "the bound, the cost and the slack",
    columns: [["Bound", "row.bound", "num"], ["Portfolio cost", "row.cost", "num"], ["Slack", "row.slack", "num"], ["Scope", "row.scope", "text"]],
    rowKey: "quantity", wrapper: "open",
  },
  {
    file: "components/coherence/CalibrationBands.tsx", tab: "coherence",
    what: "every price band as a row",
    columns: [
      ["Band", "bin.low", "text"], ["Settled", "bin.count", "num"], ["Mean price", "bin.mean_forecast", "num"],
      ["Happened", "bin.outcome_rate", "num"], ["Outcome minus price", "bin.deviation", "num"],
    ],
    rowKey: "identifier", wrapper: "folded",
  },
  {
    file: "components/coherence/CalibrationCorpus.tsx", tab: "coherence",
    what: "the corpus by series",
    columns: [
      // The cells read one SORTED array since 2026-08-26 — `corpusRows` — so
      // this table's row order is the figure's mark order and a mark can be
      // linked to a row by index. The share and the slope are fields on that
      // row now rather than sums and lookups rebuilt per cell.
      ["Series", "row.ticker", "text"], ["Settled markets", "row.count", "num"],
      ["Share of the corpus", "row.share", "num"], ["Its own slope", "row.slopeRaw", "num"],
    ],
    rowKey: "identifier", wrapper: "folded",
  },
  {
    file: "components/coherence/CalibrationScore.tsx", tab: "coherence",
    what: "the headline figures and what each reads",
    columns: [["Measure", "fact.label", "text"], ["Value", "fact.value", "num"], ["What it reads", "fact.note", "text"]],
    rowKey: "identifier", wrapper: "open",
  },
  {
    file: "components/coherence/IndexFamilies.tsx", tab: "coherence",
    what: "readings, measured and unmeasurable per family",
    columns: [
      ["Family", "row.ticker", "text"], ["Readings", "row.readings", "num"], ["Measured", "row.measured", "num"],
      ["Unmeasurable", "row.unmeasurable", "num"], ["Peak distance", "row.peak", "num"],
    ],
    rowKey: "identifier", wrapper: "folded",
  },
  {
    file: "components/coherence/LessonsPane.tsx", tab: "coherence",
    what: "which code carries a lesson and which test holds it",
    columns: [], rowKey: "identifier", wrapper: "folded", headless: true, nested: true,
  },
  {
    file: "components/coherence/PortfolioPane.tsx", tab: "coherence",
    what: "every leg through all three fee components",
    columns: [
      ["Leg", "leg.label", "text"], ["Side", "leg.direction", "text"], ["Size", "leg.size", "num"], ["Price", "leg.price", "num"],
      ["Trade fee", "leg.trade_fee", "num"], ["Rounding", "leg.rounding_fee", "num"], ["Rebate", "leg.rebate", "num"],
      ["Net fee", "leg.net_fee", "num"],
    ],
    rowKey: "identifier", wrapper: "open", total: "tfoot",
  },
  {
    file: "components/coherence/StatusPane.tsx", tab: "both",
    what: "the exchange's shards",
    columns: [["Shard", "shard.exchange_index", "text"], ["Carries", "shard.description", "text"], ["Exchange", "shard.exchange_active", "text"], ["Trading", "shard.trading_active", "text"]],
    rowKey: "identifier", wrapper: "folded",
  },
  // ------------------------------------------------------------ Markets --
  {
    file: "components/coherence/AblationPane.tsx", tab: "markets",
    what: "the replay under each configuration",
    columns: [
      ["Configuration", "row.name", "text"], ["What it models", "row.description", "text"], ["Violations", "row.violations", "num"],
      ["worth_doing", "row.worth_doing", "num"], ["Gross", "row.gross_total", "num"], ["Net", "row.net_total", "num"],
    ],
    rowKey: "identifier", wrapper: "open",
  },
  {
    file: "components/coherence/BasketSize.tsx", tab: "markets",
    what: "a basket's share of open interest by price band",
    columns: [["Family", "event.event_ticker", "text"], ["{centsOf(band.lowCc)}c", "band.share", "num"]],
    rowKey: "identifier", wrapper: "open", generated: true,
  },
  {
    file: "components/coherence/DispersionTable.tsx", tab: "markets",
    what: "the maker panel per market",
    columns: [
      ["Market", "", "text"], ["Quotes", "", "num"], ["Usable", "", "num"], ["Median", "", "num"],
      ["Lowest to highest", "", "num"], ["Spread between makers", "", "num"], ["Median maker width", "", "num"],
      ["Crossed", "", "num"], ["Band the legs leave", "", "num"], ["Share of it used", "", "num"],
      ["Panel", "", "marks"], ["Notes", "", "text"],
    ],
    rowKey: "identifier", wrapper: "folded", cellsElsewhere: true, cellFold: true,
  },
  {
    file: "components/coherence/FeesPane.tsx", tab: "markets",
    what: "every fill's three fee components",
    columns: [
      ["Fill", "index + 1", "text"], ["Trade fee", "fill.trade_fee", "num"], ["Rounding fee", "fill.rounding_fee", "num"],
      ["Rebate", "fill.rebate", "num"], ["Net", "fill.net", "num"], ["Notional", "fill.notional", "num"],
    ],
    rowKey: "identifier", wrapper: "folded", total: "tfoot",
  },
  {
    file: "components/coherence/RfqPane.tsx", tab: "markets",
    what: "what each RFQ state means",
    columns: [["State", "row.mark", "text"], ["This read", "row.state", "marks"], ["What it means", "row.means", "text"], ["What it is not", "row.not", "text"]],
    rowKey: "identifier", wrapper: "folded", nested: true,
  },
  {
    file: "components/coherence/ShellCommandReference.tsx", tab: "markets",
    what: "the shell's commands",
    columns: [["Name", "ls", "text"], ["What it reads", "A path", "text"], ["When it has no answer", "Answers", "text"]],
    rowKey: "identifier", wrapper: "folded",
  },
  {
    file: "components/coherence/UniversePane.tsx", tab: "markets",
    what: "every outcome as quoted",
    columns: [
      ["Outcome", "market.yes_sub_title", "text"], ["Strike", "describeStrike", "text"], ["YES bid", "market.yes_bid", "num"],
      ["YES ask", "market.yes_ask", "num"], ["Spread", "market.spread", "num"], ["Grid", "market.price_grid", "num"],
    ],
    rowKey: "identifier", wrapper: "folded", nested: true,
  },
  {
    file: "components/coherence/surface/DistributionView.tsx", tab: "markets",
    what: "a reading table of the lattice's facts",
    columns: [["Reading", "fact.label", "text"], ["Value", "fact.value", "num"], ["What it says", "fact.says", "text"]],
    rowKey: "identifier", wrapper: "open",
  },
  {
    file: "components/coherence/surface/StakeView.tsx", tab: "markets",
    what: "the admitted stakes",
    columns: [
      ["Outcome", "stake.label", "text"], ["Admitted", "stake.admitted", "marks"], ["Measure", "stake.probability", "num"],
      ["Price", "stake.price", "num"], ["Edge", "stake.edge", "num"], ["Full Kelly", "stake.full_fraction", "num"],
      ["Stake", "stake.fraction", "num"],
    ],
    rowKey: "identifier", wrapper: "open",
  },
];
