/**
 * Every table on the two engine tabs, declared: what it is, what each column
 * is headed, what kind of cell sits under it, and how it is framed.
 *
 * Twenty-eight `<table>` elements in twenty-six files, measured on 2026-09-02 by
 * reading every `<table` under `components/coherence/` (surface included,
 * Diffusion excluded — it has its own contract). `engine-data-contract.test.ts`
 * derives the same list by scanning, so a table added without a row here is
 * red, and a row here for a table that has gone is red too.
 *
 * WHY DECLARE RATHER THAN INFER. A header-text match cannot tell a row label
 * from a paraphrase, a count column from an identifier, or a marks column from
 * a cell that happens to hold a glyph — `copy-audit-engines` records four
 * columns a first pass flagged wrongly for exactly that reason. So each column
 * says what it is, and the test holds the markup to the declaration.
 *
 *   kind "num"   — a quantity: `.num` on the `<th>` and every `<td>`, right-aligned
 *                  in tabular figures, dash (never blank, never 0) when null.
 *   kind "text"  — words, left. An identifier (a ticker, a shard index, a fill
 *                  ordinal, a band label) is text even when it is digits: it
 *                  names a row, it is not measured.
 *   kind "marks" — the house vocabulary ● ▲ ✕ ○ ◌ ✓ →, always mark + word.
 *
 *   rowKey "quantity" — the ONE table whose row header is itself a number
 *                       (`CombosBounds`' bound) and carries `.num`.
 */

export type Kind = "text" | "num" | "marks";

export interface TableDecl {
  /** Web-relative path. */
  file: string;
  /** Which `<table>` in the file, when it holds more than one. */
  nth?: number;
  tab: "coherence" | "markets" | "both";
  what: string;
  /** [header label, a token the cell beneath must contain, what kind of cell]. */
  columns: ReadonlyArray<readonly [label: string, token: string, kind: Kind]>;
  rowKey: "identifier" | "quantity";
  /** Whether the table sits inside a `<details>` in its own file. */
  wrapper: "open" | "folded";
  /** A key/value table with no `<thead>`: its row headers are its only headers. */
  headless?: true;
  /** Header cells generated by a `.map` — the count cannot be compared with the cells. */
  generated?: true;
  /** Rows rendered by a child component; the cell check reads nothing here. */
  cellsElsewhere?: true;
  /** Inside a bordered card — the frame is the card's, and the table drops its own. */
  nested?: true;
  /** A `<details>` inside a cell (DispersionTable's per-row fold). */
  cellFold?: true;
  /** The total row, and the one spelling it is allowed. */
  total?: "tfoot";
}

export const TABLES: readonly TableDecl[] = [
  // ------------------------------------------------------------- Proofs --
  {
    file: "components/coherence/CertificateViews.tsx", nth: 0, tab: "coherence",
    what: "the six quantities the certificate decides on",
    columns: [["Quantity", "row.label", "text"], ["Value", "row.of(data)", "num"], ["What it decides", "row.decides", "text"]],
    rowKey: "identifier", wrapper: "folded",
  },
  {
    file: "components/coherence/ConstraintLadder.tsx", tab: "coherence",
    what: "every evaluated constraint behind the six tightest proof checks",
    columns: [
      ["Constraint", "KIND_WORD[constraint.kind]", "text"],
      ["Subject", "constraint.subject", "text"],
      ["Room", "money(constraint.slack)", "num"],
      ["Result", "constraint.violated", "marks"],
    ],
    rowKey: "identifier", wrapper: "folded",
  },
  {
    file: "components/coherence/SolverProofLoom.tsx", tab: "coherence",
    what: "the named quote checks attached to the exact solver run",
    columns: [
      ["Check", "row.family", "text"], ["Reason", "row.because", "text"],
      ["Cost", "money(row.cost)", "num"], ["Bound", "money(row.bound)", "num"],
      ["Room", "money(row.slack)", "num"], ["Result", "row.testable", "text"],
    ],
    rowKey: "identifier", wrapper: "folded",
  },
  {
    file: "components/coherence/ProofsMethodMap.tsx", tab: "coherence",
    what: "the inputs, operation, output, and hand-off for each proof stage",
    columns: [], rowKey: "identifier", wrapper: "open", headless: true, nested: true,
  },
  {
    // Both combos tables moved to `ParlaysView.tsx` on 2026-08-26 with the
    // view they belong to; the leg table travels inside the card behind each
    // parlay's fold.
    file: "components/coherence/ParlaysView.tsx", nth: 0, tab: "coherence",
    what: "a parlay's legs",
    columns: [
      ["Leg", "leg.ticker", "text"], ["Must land", "leg.side", "text"], ["Implied p", "leg.probability", "num"],
      ["Buy cost", "leg.buy_cost", "num"], ["Opposite cost", "leg.opposite_cost", "num"],
    ],
    rowKey: "identifier", wrapper: "folded",
  },
  {
    file: "components/coherence/BandsTable.tsx", tab: "coherence",
    what: "the loaded parlays available to the local Fréchet-band inspector",
    columns: [
      ["Parlay", "parlayName(combo)", "text"], ["Legs", "combo.legs.length", "num"],
      ["Allowed range", "rangeLabel(combo)", "num"], ["Quote", "priceLabel(combo.price)", "num"],
      ["Position", "readingLabel(combo)", "marks"],
    ],
    rowKey: "identifier", wrapper: "open",
  },
  {
    file: "components/coherence/CombosBounds.tsx", nth: 0, tab: "coherence",
    what: "the legs a bound is built from",
    columns: [["Leg", "leg.label", "text"], ["Direction", "leg.buy_cost", "text"], ["Side", "leg.side", "text"], ["Cost", "leg.buy_cost", "num"]],
    rowKey: "identifier", wrapper: "open",
  },
  {
    file: "components/coherence/MurphyTermTable.tsx", tab: "coherence",
    what: "the signed Murphy decomposition glossary",
    columns: [
      ["Sign", "term.sign", "text"], ["Term", "term.name", "text"], ["Value", "term.raw", "num"],
      ["Good direction", "term.direction", "text"], ["Meaning", "term.meaning", "text"],
    ],
    rowKey: "identifier", wrapper: "folded",
  },
  {
    file: "components/coherence/CalibrationBands.tsx", tab: "coherence",
    what: "every price band as a row",
    columns: [
      ["Band", "bin.low", "text"], ["Settled", "bin.count", "num"], ["Mean price", "bin.mean_forecast", "num"],
      ["Happened", "bin.outcome_rate", "num"], ["Outcome minus price", "bin.deviation", "num"],
    ],
    rowKey: "identifier", wrapper: "folded",
  },
  {
    file: "components/coherence/CalibrationCorpus.tsx", tab: "coherence",
    what: "the corpus by series",
    columns: [
      // The cells read one SORTED array since 2026-08-26 — `corpusRows` — so
      // this table's row order is the figure's mark order and a mark can be
      // linked to a row by index. The share and the slope are fields on that
      // row now rather than sums and lookups rebuilt per cell.
      ["Series", "row.ticker", "text"], ["Settled markets", "row.count", "num"],
      ["Share of the corpus", "row.share", "num"], ["Its own slope", "row.slopeRaw", "num"],
    ],
    rowKey: "identifier", wrapper: "folded",
  },
  {
    file: "components/coherence/CalibrationScore.tsx", tab: "coherence",
    what: "the headline figures and what each reads",
    columns: [["Measure", "fact.label", "text"], ["Value", "fact.value", "num"], ["What it reads", "fact.note", "text"]],
    rowKey: "identifier", wrapper: "open",
  },
  {
    file: "components/coherence/IndexFamilies.tsx", tab: "coherence",
    what: "readings, measured and unmeasurable per family",
    columns: [
      ["Family", "row.ticker", "text"], ["Readings", "row.readings", "num"], ["Measured", "row.measured", "num"],
      ["Unmeasurable", "row.unmeasurable", "num"], ["Peak distance", "row.peak", "num"],
    ],
    rowKey: "identifier", wrapper: "folded",
  },
  {
    file: "components/coherence/GroupPins.tsx", tab: "coherence",
    what: "guarded module and pinning suite counts for every lesson in the selected slice",
    columns: [
      ["Lesson", "cell.lesson.title", "text"], ["Taught in", "sectionLabel(cell.lesson.pane)", "text"],
      ["Guarded modules", "cell.modules", "num"], ["Pinning suites", "cell.suites", "num"],
      ["Suite coverage", "coverageLabel(cell)", "marks"], ["Full lesson", "onInspect(cell.lesson)", "text"],
    ],
    rowKey: "identifier", wrapper: "open",
  },
  {
    file: "components/coherence/LessonsPane.tsx", nth: 0, tab: "coherence",
    what: "the conditions under which the selected lesson holds or fails",
    columns: [["Condition", "When it holds", "text"], ["Technical reading", "lesson.whenItHolds", "text"]],
    rowKey: "identifier", wrapper: "open", nested: true,
  },
  {
    file: "components/coherence/LessonsPane.tsx", nth: 1, tab: "coherence",
    what: "which code carries the selected lesson and which tests pin it",
    columns: [], rowKey: "identifier", wrapper: "open", headless: true, nested: true,
  },
  {
    file: "components/coherence/LessonsPane.tsx", nth: 2, tab: "coherence",
    what: "every lesson in the selected curriculum slice",
    columns: [
      ["Lesson", "lesson.title", "text"], ["Status", "lesson.shipped", "marks"],
      ["Taught in", "sectionLabel(lesson.pane)", "text"], ["Technical reading", "lesson.summary", "text"],
      ["Formula", "lesson.formula", "text"], ["Open detail", "onOpen", "text"],
    ],
    rowKey: "identifier", wrapper: "open", cellsElsewhere: true,
  },
  {
    file: "components/coherence/ParlayLegs.tsx", tab: "coherence",
    what: "the exact required legs behind the selected parlay bound",
    columns: [
      ["#", "index + 1", "num"], ["Required leg", "leg.ticker", "text"],
      ["Must land", "leg.side", "text"], ["Price", "leg.text", "num"],
      ["Effect on range", "parlayLegBandRole", "text"],
    ],
    rowKey: "identifier", wrapper: "open",
  },
  {
    file: "components/coherence/PortfolioPane.tsx", tab: "coherence",
    what: "every leg through all three fee components",
    columns: [
      ["Leg", "leg.label", "text"], ["Side", "leg.direction", "text"], ["Size", "leg.size", "num"], ["Price", "leg.price", "num"],
      ["Trade fee", "leg.trade_fee", "num"], ["Rounding", "leg.rounding_fee", "num"], ["Rebate", "leg.rebate", "num"],
      ["Net fee", "leg.net_fee", "num"],
    ],
    rowKey: "identifier", wrapper: "open", total: "tfoot",
  },
  // ------------------------------------------------------------ Markets --
  {
    file: "components/coherence/OrderBookDepthHeatmap.tsx", tab: "markets",
    what: "cumulative YES and NO ladder depth at every observed price",
    columns: [["Side", "side", "text"], ["YES px {fromCenticents(level.cc)}", "level[side]", "num"]],
    rowKey: "identifier", wrapper: "open", generated: true,
  },
  {
    file: "components/coherence/BooksInstruments.tsx", tab: "markets",
    what: "exact native and mirrored book levels behind the depth explorer",
    columns: [
      ["Side", "row.side.toUpperCase()", "text"], ["Native", "row.nativePrice", "num"],
      ["YES axis", "row.yesPrice", "num"], ["At level", "row.size", "num"],
      ["At or better", "row.depth", "num"],
    ],
    rowKey: "identifier", wrapper: "folded",
  },
  {
    file: "components/coherence/DispersionTable.tsx", tab: "markets",
    what: "the maker panel per market",
    columns: [
      ["Market / request", "", "text"], ["Quotes", "", "num"], ["Usable", "", "num"], ["Median", "", "num"],
      ["Lowest to highest", "", "num"], ["Spread between makers", "", "num"], ["Median maker width", "", "num"],
      ["Crossed", "", "num"], ["Band the legs leave", "", "num"], ["Share of it used", "", "num"],
      ["Panel", "", "marks"], ["Notes", "", "text"],
    ],
    rowKey: "identifier", wrapper: "folded", cellsElsewhere: true, cellFold: true,
  },
  {
    file: "components/coherence/FeesPane.tsx", tab: "markets",
    what: "every fill's three fee components",
    columns: [
      ["Fill", "index + 1", "text"], ["Trade fee", "fill.trade_fee", "num"], ["Rounding fee", "fill.rounding_fee", "num"],
      ["Rebate", "fill.rebate", "num"], ["Net", "fill.net", "num"], ["Notional", "fill.notional", "num"],
    ],
    rowKey: "identifier", wrapper: "folded", total: "tfoot",
  },
  {
    file: "components/coherence/RfqPane.tsx", tab: "markets",
    what: "what each RFQ state means",
    columns: [["State", "row.mark", "text"], ["This read", "row.state", "marks"], ["What it means", "row.means", "text"], ["What it is not", "row.not", "text"]],
    rowKey: "identifier", wrapper: "folded", nested: true,
  },
  {
    file: "components/coherence/ShellCommandReference.tsx", tab: "markets",
    what: "the shell's commands",
    columns: [["Name", "ls", "text"], ["What it reads", "A path", "text"], ["When it has no answer", "Answers", "text"]],
    rowKey: "identifier", wrapper: "folded",
  },
  {
    file: "components/coherence/ShellReadings.tsx", tab: "markets",
    what: "derived namespace files grouped by empty-result semantics",
    columns: [["Reading", "file.name", "text"], ["What it reads", "file.reads", "text"]],
    rowKey: "identifier", wrapper: "open", nested: true,
  },
  {
    file: "components/coherence/UniversePane.tsx", tab: "markets",
    what: "every outcome as quoted",
    columns: [
      ["Outcome", "market.yes_sub_title", "text"], ["Strike", "describeStrike", "text"], ["YES bid", "market.yes_bid", "num"],
      ["YES ask", "market.yes_ask", "num"], ["Spread", "market.spread", "num"], ["Grid", "market.price_grid", "num"],
    ],
    rowKey: "identifier", wrapper: "folded", nested: true,
  },
  {
    file: "components/coherence/surface/DistributionView.tsx", tab: "markets",
    what: "a reading table of the lattice's facts",
    columns: [["Reading", "fact.label", "text"], ["Value", "fact.value", "num"], ["What it says", "fact.says", "text"]],
    rowKey: "identifier", wrapper: "open",
  },
  {
    file: "components/coherence/surface/StakeView.tsx", tab: "markets",
    what: "the admitted stakes",
    columns: [
      ["Outcome", "stake.label", "text"], ["Admitted", "stake.admitted", "marks"], ["Measure", "stake.probability", "num"],
      ["Price", "stake.price", "num"], ["Edge", "stake.edge", "num"], ["Full Kelly", "stake.full_fraction", "num"],
      ["Stake", "stake.fraction", "num"],
    ],
    rowKey: "identifier", wrapper: "open",
  },
];
